xsf/xeps

gen.py, xeputil.py
=> temporary fix to realize the repo root is now the current directory

xep.ent
Just putting Surevine email/jid in.
=> Update dcridland entity

xep-0293.xml, xep-0294.xml
Final Council tallies completed in 2015-05, but advancement didn't actually happen!
=> Advance XEPs -0293 and -0294 to Draft.

inbox/jingle-http-transport.xml
Submitted on behalf of Lance Stout
=> ProtoXEP Jingle HTTP Transport Method

inbox/message-deletion.xml
Submitted on behalf of Lance Stout
=> ProtoXEP Message Deletion

inbox/entityversioning.xml
Editorial change in a protoxep.
s/parcial/partial/
=> Typo fix in entity versioning

xep.xsl
Guess you want this one too...
=> Also use the prettify.js from the extentions directory.

inbox/tls-srv.xml
I've updated this ProtoXEP as was discussed in the council meeting and the mailing list.
Rendered version can be found at https://burtrum.org/xeps/tls-srv.html
=> Update SRV records for XMPP over TLS draft

inbox/jid-mention.xml
On behalf of Jérôme Poisson.
Note copyright affirmation and assignment confirmed: < http://mail.jabber.org/pipermail/editor/2016-January/000446.html >
=> ProtoXEP Jid Mentions -- initial draft

inbox/multistage-ibr.xml
On behalf of Stephen Paul Weber.
=> ProtoXEP Multi-Stage-IBR

xep-0313.xml
Change the couple of :0 to :1.
=> Fix remaining :0 namespaces in MAM

xep-0363.xml
s/responsd/responds/
/cc @iNPUTmice
=> XEP-0363: Typo fix

xep-0166.xml
=> XEP-0166: Fix draft-ietf-stox-media ref

xep-0260.xml
=> XEP-0260: Fix broken ICE-TCP ref

xep-0375.xml
Move XEP-0352 to the mobile suite and add XEP-0198, and XEP-0357.
=> XEP-0375: Add a mobile compliance suite

xep-README.xml
Update to match the current process. Submitting a PR before I merge to get @ashward's approval in case I screwed anything up.
Other sections are still wrong; I just updated the section for the thing I just did as I'm reasonably sure the steps are correct. Other sections can be updated later as we do them.
=> Fix the updating an XEP section of the README

xep-0363.xml
Spotted one while reading the XEP, found a few more with a spell-checker!
=> XEP-0363: fix a few typos

xep-0366.xml
* Remove invalid email for Doug (I do not have updated contact info for him)
* Use the XML entity for my author info
* Typo fixes
=> XEP-0366: Fix typos

inbox/pars.xml
This corresponds to the email submission and is based on the following
commit history:
commit f1ec69a95a0b6e5784ebd1250ab5ec81ee8913a6
Author: Georg Lukas <georg@op-co.de>
Date:   Thu Jun 16 12:24:27 2016 +0200
PARS: fix typo
commit 01115a14c3ac538b2cda23d6baddd1dc7e2edc32
Author: Georg Lukas <georg@op-co.de>
Date:   Thu Jun 16 12:14:36 2016 +0200
PARS: add subsections to ImplNotes, specify landing page capture
commit 97ba814bf733265d8a5250042043a59caaddc581
Author: Georg Lukas <georg@op-co.de>
Date:   Thu Jun 16 12:14:01 2016 +0200
PARS: blockquote -> div.example
commit bdb640a14cb3d5e397fd6d2cfc63765ab12290e8
Author: Georg Lukas <georg@op-co.de>
Date:   Thu Jun 16 12:13:40 2016 +0200
PARS: make xmpp: strong
commit b63a4eaa368c4c3a7ab29024c3bce4fd30adca3c
Author: Georg Lukas …
=> Add Pre-Authenticated Roster Subscription to inbox

xep-0084.xml
Fixes a broken namespace pointed out by Huan Nguyen.
=> XEP-0084: Fix broken namespace in example

xep-README.xml
Still needs work, but this at least clarifies / fixes a few things.
=> Update the section on accepting an XEP

xep-0375.xml
Based on feedback from the mailing list (/cc @dwd) and @iNPUTmice.
=> XEP-0375: Refactor tables to be feature-focused

xep-0373.xml
for 7e2b3c144df89df1664b6e9c2d656267863793e2.
=> XEP-0373: Add Brian Cully to acknowledgements

xep-0053.xml
=> Introduce 'Proposed' status in XEP-0053

xep-0376.xml
Added some concrete protocol for the very basic use-cases.
=> Update PAM to have some actual protocol

xep-0361.xml
=> Fix typo in dependencies

inbox/eme.xml
Received by email, IPR confirmed onlist.
=> Inbox: Add Explicit Message Encryption XEP.

xep-0369.xml
Sorry for having done a PR before the patch got merged, this is a rebase on top of current master.  Each commit is reviewable separately as a single unit.
=> XEP-0369 misc editor fixes

xep-0369.xml
First set of changes that I made during a major review on a flight today. This one is mostly phrasing and grammar, the next few will be content, examples, and proposed changes that will need discussion.
It probably conflicts with #229. I will rebase and tweak things after that's merged.
=> XEP-0369: Phrasing and grammar tweaks

xep-0060.xml
It's not just more consistent but also easier to implement like this in most cases probably ;)
=> XEP-0060: be more consistent with reply

xep-0347.xml
=> XEP-0347: Replace external image with data URI.

xep-0030.xml
Listing a disco#info feature in a disco#info answer is a MUST when it isn’t an error, thanks gkiagia.
=> XEP-0030 fixes

xep-0288.xml
Also tweak example formatting
This fix is editorial in nature.
=> XEP-0288: Fix syntax highlighting

inbox/burner.xml
> A mechanism by which users may request arbitrary anonymizing "burner" JIDs for short term use.
=> Add initial draft of burner JID XEP to inbox

inbox/spoiler.xml
Ready to merge; just waiting on CI to give the green light.
=> Accept new "spoilers" protoxep

xep-0322.xml
Formatting and XML fixes for EXI. Also removes the (old) last call as per [this council agenda card](https://trello.com/c/bylZxCL3/121-exi-last-call).
=> XEP-0322: Formatting and XML fixes

xep-0300.xml, xep-0371.xml
End the two last calls expiring today.
=> XEP-0371, XEP-0300: Last call has expired

inbox/burner.xml
=> Clarify text in burner JID protoxep

xep-0003.xml
Fix several unescaped cdata less than and greater than signs.
=> XEP-0003: Fix minor XML issues

xep-0381.xml
=> Publish IoT SIG as XEP-0381

xep-0006.xml, xep-0007.xml, xep-0008.xml, xep-0009.xml, xep-0010.xml, xep-0014.xml, xep-0015.xml, xep-0018.xml
Only one minor content change (to XEP-0009) that fixes some unescaped characters.
=> Lots of DTD fixes

xep-0369.xml
Clarify Direct PubSub acces to each node type
=> XEP 0369 - update to version 0.6.1

xep-0366.xml
=> XEP-0366: Fix whitespace and DTD issues

xep-0369.xml
Editorial Changes (Georg Lukas Review)
Improve 1:1 Conversion
Sort out MIX Proxy and Presence Update
=> XEP-0369 (MIX) Update to 0.6.2

xep-0366.xml
Probably more coming. Checking this against CI.
=> XEP-0366: Editing for spelling, tone, and grammar

xep-0320.xml
=> XEP-0320: Remove old last call

xep-0369.xml
Add Update and Distribution to Table 3;
Correct from in messages from channel;
Use XEP-0297 in message forwarding;
Update Dependent XEPs
=> XEP-0369 (MIX) - update to version 0.6.3

xep-0017.xml, xep-0035.xml, xep-0036.xml, xep-0037.xml, xep-0038.xml, xep-0039.xml, xep-0040.xml, xep-0041.xml, xep-0042.xml, xep-0043.xml, xep-0044.xml, xep-0046.xml, xep-0047.xml, xep-0051.xml, xep-0052.xml, xep-0056.xml, xep-0057.xml, xep-0058.xml
All editorial (does have some minor content changes where links and things were broken). Waiting for CI.
=> Fix DTD check for 0017–0058

xep-0061.xml, xep-0062.xml, xep-0063.xml, xep-0064.xml, xep-0067.xml, xep-0069.xml, xep-0074.xml, xep-0075.xml, xep-0087.xml, xep-0097.xml
=> XEP-0061–XEP-097: DTD fixes

xep-0101.xml, xep-0102.xml, xep-0103.xml, xep-0105.xml, xep-0106.xml, xep-0109.xml, xep-0119.xml, xep-0120.xml, xep-0121.xml, xep-0123.xml, xep-0125.xml, xep-0133.xml, xep-0137.xml, xep-0146.xml, xep-0151.xml, xep-0152.xml, xep-0157.xml, xep-0162.xml, xep-0171.xml, xep-0179.xml, xep-0180.xml, xep-0185.xml, xep-0188.xml, xep.dtd
I put the XEP-0188 changes in a separate comit because fixing them required removing a lot of manual syntax highlighting which means information about the authors intent may be lost. It's deferred and the highlighting was broken anyways, so I'm not sure we care, but it's nice to know if we ever are digging through the history later.
=> DTD fixes for XEP-01xx

.travis.yml, Makefile, xep-0017.xml, xep-0024.xml, xep-0037.xml, xep.ent
Does this even work this way? Do we need to consult a lawyer?
Board agenda item: https://trello.com/c/sXc4y6Yl
=> Fix legal notice on old public domain XEPs

xep-0345.xml
This ends an old last call that was apparently missed. I'll raise it on list to see if we want to bring this back or not.
Fixes #339
=> XEP-0345: End old last call

resources/xmpp.pdf
Somehow there's an HTML file where xmpp.pdf should be which is breaking PDF builds of the XEP. xmpp-text.pdf is fine.
=> Fix broken xmpp.pdf

Makefile
Let the makefile build the references and examples.
=> Add targets to build IETF refs and examples in Makefile

xep.xsl
This reverts commit ee2544758c8bf0b26ec626993f7a510b77260700, reversing
changes made to 2c4b42dbd1c8d09fbd7b89d8ac6776615baacbe5.
As @tfar pointed out, this is duplicating numbers when building some specs.
=> Revert "Merge pull request #360 from SamWhited/unique_ref_notes"

xep-0215.xml, xep-0233.xml, xep-0264.xml, xep-0286.xml, xep-0292.xml, xep-0298.xml, xep-0318.xml, xep-0320.xml, xep-0323.xml, xep-0324.xml, xep-0325.xml, xep-0326.xml, xep-0330.xml, xep-0331.xml, xep-0333.xml, xep-0334.xml, xep-0335.xml, xep-0336.xml
Lots of old XEPs that haven't been touched in 12+ months and need deferring. Some of these are widely used and should probably be advanced; I'll ask the various people involved if they want to continue pushing them forward or try to advance them and we can undefer them if anyone wants to take over and champion an XEP on a case by case basis.
Fixes #369
=> Defers many old XEPs

xep-0186.xml, xep-0280.xml, xep-0327.xml, xep-0332.xml, xep-0352.xml
End old LCs for:
- xep-0186
- xep-0280
- xep-0327
- xep-0332
- xep-0352
=> End several old Last Calls

xep-0186.xml
Also possibly a candidate to advance
=> XEP-0186: Defer after years of inactivity

xep-0286.xml
Some simple clarifications to XEP-0286. Also a retab / rewrap, which makes the diff a bit nasty; probably best to look at one commit at a time.
=> XEP-0286 clarifications

xep-0352.xml
Defering since it's been stuck in perpetual (expired) LC without updates for over a year.
=> XEP-0352: Defer due to inactivity

xep-0270.xml, xep-0333.xml, xep-0368.xml
Issue LC for XEP-0368 and XEP-0333, obsolete XEP-0270
=> Latest Council Meeting Changes

xep-0363.xml
also some slight syntax changes and a namespace bump
=> HTTP Upload:  added ability to provide additional HTTP header fields on slot assignment

inbox/cs2017.xml
Added these as a new protoxep at someones request, but I'm happy to bump the date of the 2016 ones too.
=> Add 2017 Compliance Suites to the inbox

xep-0280.xml, xep-0334.xml, xep-0352.xml
Issue LCs for:
* xep-0352
* xep-0334
* xep-0280
=> Several lCs

inbox/sasl2.xml
As discussed at the Summit.
I declare that:
* I am legally able to assign copyright to the XMPP Standards Foundation
* I shall do so on acceptance by the Council
* I shall perfect as required.
Anything else I need to say?
=> SASL2 - New SASL Profile

inbox/ibr2.xml
First draft of a new multi-stage in-band registration and recovery mechanism.
Still todo:
* Consider adding account deletion?
* Add some form of error (not just cancelation)?
* Define a proof-of-work challenge type
* Define an OOB data challenge type
=> Add IBR2 to inbox

xep-0333.xml, xep-0368.xml
Extend the LCs while feedback is addressed as per the 2017-02-15 council meeting.
=> XEP-0333, XEP-0368: Extend LC until 2017-02-22

announce.py, deferred.py, inxep.py, lastcall.py
We've moved to HTTPS everywhere. This diff reflects the change in the email announcement generator scripts.
=> gen-scripts: Encrypt all URLs ;-)

xep-0313.xml
Human-readable diff available here: https://matthewwild.co.uk/uploads/xep-0313-r6.diff.html
=> XEP-0313: Revision 6.0 update

xep-0233.xml, xep-0280.xml, xep-0333.xml, xep-0334.xml, xep-0352.xml
Extend a few LCs again as discussed in the council meeting. Voting to happen next week on any that have had the feedback addressed.
=> Extend lcs

xep-0313.xml
=> XEP-0313: Revision 0.6.1 (MUC message spoofing fix)

xep-0233.xml
This change was missed in the last PR
=> Updated revision

xep-0333.xml
Move back to experimental while @iNPUTmice makes changes.
=> XEP-0333: Back to experimental pending changes

xep-0368.xml
Also various editorial formatting fixes.
/cc @moparisthebest for final review
=> XEP-0368: Advance to draft

xep-0369.xml
Editorial Changes (mainly from Georg Lukas);
Change to new syntax for proxy JIDs;
Clarify MAM archive on Send;
Extend to sort Selected JID visibility;
Add examples of lookup read JID from proxy JID;
=> MIX (XEP-0369) to version 0.9

xep-0323.xml, xep-0324.xml, xep-0325.xml, xep-0326.xml
Retract IoT XEPs at the request of the author.
=> Retract IoT XEPs

xep-0016.xml, xep-0191.xml
Deprecate XEP-0016 in favor of XEP-0191 per a vote of the council.
=> XEP-0016: Deprecate

xep-0369.xml
Editorial Changes (addressing comments  from Timothée Jaussoin)
=> MIX (XEP-0369) update to 0.9.1

xep-0234.xml
=> XEP-0234: Fix the schema and add a missing anchor

xep-0359.xml
I have tested the schema using `xmllint` on a few valid and invalid examples.
=> XEP-0359: Add a schema and fix a typo

xep-0357.xml
(Merge after #483)
Kev has agreed to taking over authorship for the XEP.
=> XEP-0357 author change

xep-0133.xml
Fix an example an anonymous someone pointed out in the prosody MUC.
=> XEP-0133: fix broken node in example

xep-0384.xml
These are the same changes @iNPUTmice proposed in #470, with a small change in the wording.
=> Omemo signal protocol

xep-0278.xml
Added Support for TURN Discovery and Credentials Retrieval
Inspired by: https://tools.ietf.org/html/draft-uberti-rtcweb-turn-rest-00
=> XEP-0278: Added Support for TURN

README.md
I essentially wrote down what I did when I merged a bunch of PRs recently. I’ll put this here in case anyone wants to take a look at it, otherwise I’ll simply merge it next week or so.
=> Extend the readme with new tooling and workflow

inbox/bmh.xml
Rendered version: http://geekplace.eu/xeps/xep-bmh/xep-bmh.html
=> Add "Body Markup Hints" ProtoXEP to inbox

xep-0071.xml
In response to the [recent thread on standards@](https://mail.jabber.org/pipermail/standards/2017-October/033546.html), I propose a clarification of the Security Considerations.
=> XEP-0071: make security considations much clearer

xep-0387.xml
Bumps the year on the compliance suites to 2018.
=> XEP-0387: bump compliance suite year to 2018

inbox/styling.xml
Initial changes (not all editorial) based on list feedback.
=> styling: update based on list feedback

xep-0387.xml
Someone just pointed out to me that the address format RFC was wrong.
=> XEP-0387: update address format RFC

xep-0186.xml
Supersedes #550
(editor tweaks to update the LC date and add a commit message)
=> XEP-0186: Address LC feedback

xep-0363.xml
* Added `<retry/>` element to error response
* Extend Security Considerations
=> XEP-0363: amend security considerations and introduce retry element

inbox/pep-vcard-conversion.xml
proto xep.
rendered version here: https://gultsch.de/files/pep-vcard-conversion.html
=> added pep-vcard-conversion to inbox

xep-0126.xml, xep-0186.xml
Deprecate and mark XEP-0126 as superseded by XEP-0186.
=> XEP-0126: Deprecated by vote of the council

xep-0366.xml, xep-0387.xml
Also defer another XEP of mine that hasn't been updated in 12 months.
=> XEP-0387: retracted by the author

xep-0387.xml
=> XEP-0387: Add myself as author and move back to Proposed

xep-0363.xml
* White listed a few select headers
* removed some inappropriate use of normative language
=> XEP-0363: Http upload 0.5

xep-0071.xml
=> XEP-0071: move to obsolete

xep-0137.xml
Forgot to push that this one was also deprecated.
=> XEP-0137: deprecated by the council

xep-0369.xml
I've changed the apostrophes in the XML code and add two of them missing.
=> XEP-0369: fix typo error

inbox/bookmarks2.xml
Password removal as suggested by @SamWhited in the list.
Updated security considerations as suggested by @iNPUTmice 
@dwd What do you think?
=> bookmarks2: remove password element, add examples, update security considerations

xep-0385.xml
s/exiting/existing/
s/contant/content/
s/availablity/availability/
=> XEP-0385: Fix typos

xep-0373.xml
Diff at http://geekplace.eu/xeps/xep-openpgp/diff.html
=> Update "XEP-0373: OpenPGP for XMPP" to 0.3.0

xep-0384.xml
Is there anything else needed for this to pass?
=> xep-0384: fix attribute names in schema

xep-0060.xml
Also release the next patch version.
=> XEP-0060: Fix two small issues in the schema

xep-0401.xml
=> XEP-0401: Typo in example 5 title

xep-0369.xml
=> XREP-0369 Mandatory/Optional table

inbox/omemo-media-sharing.xml
Informational XEP on how OMEMO capable clients currently handle media sharing.
=> OMEMO Media Sharing

inbox/fsn.xml
Remark:
Added Requirements and Acknowledgements, simplified some definitions and added
rules for Client State Indication.
=> inbox/fsn.xml: New revision (0.0.3)

xep-0402.xml
=> XEP-0402: Add missing dependency

xep-0045.xml
Questions to Council:
* Merge or not?
* Minor or Patch version number bump?
=> XEP-0045: Add implementation note about {jabber:x:conference}x payload

xep-0283.xml
=> xep-0283: Fix example JID

inbox/muc-avatars.xml, xep-0398.xml, xep-0410.xml
Contains #700 and #699, which AFAICT are the only mergeable PRs currently.
=> Meta-merge

xep-0060.xml
That shows what happens when the client requests some items from a node and none are present.
=> XEP-0060: Add an example on returning fewer items than requested

xep-0205.xml
Thanks Zash and Lyn for noticing!
=> XEP-0205: Fix a namespace typo in an example

inbox/buttons.xml
Overhyped canned response thing.
=> ProtoXEP Buttons: A XEP about clicking things

xep-0363.xml
Added a short implementation note regarding the use of HTTP Upload in web clients
=> XEP-0363: added implementation note on CORS header

xep-0405.xml
Discovery on Account rather than Server;
Add participant ID to roster;
=> MIX-PAM (XEP-0405) update

xep-0363.xml
Here is a [render of those changes](https://gultsch.de/files/xep-0363.html).
=> XEP-0363: Added security consideration regarding proper isolation

xep-0394.xml
An attempt to adopt the XEP, as Jonas suggested.
=> Adopt deferred XEP-0394.

xep-0412.xml
Fix stupid mistake in previous version, add another missed suggestion.
=> XEP-0412: update to version 0.4.0

xep.ent
Describes my move to Threads Styling
=> Update my entry in xep.ent

xep-0386.xml
As Matt requested at the summit.
=> Allow eliding of <unread> in XEP-0386

xep-0410.xml
This WIP PR is meant to accumulate feedback from the XEP-0410 LC.
=> XEP-0410: pre-LC and LC feedback

xep-0261.xml
Must match with one in ``<transport>``
=> XEP-0261: Fixed sid in example 10.

inbox/automatic-trust-transfer.xml
This is a first draft of *Automatic Trust Transfer*.
There is also an [HTML version](https://olomono.github.io/xeps/build/xep-xxxx-automatic-trust-transfer.html) and an [implementation](https://github.com/siacs/Conversations/pull/3400) of the XEP available.
=> Automatic Trust Transfer

xep-0369.xml
Address Dave Cridland Review Comments
Remove MIX xmlns from pubsub channel info &lt;item/&gt; example;
Make Message Archiving Optional;
Clarify that participant node only contains real JIDs;
=> Mix CORE - XEP-0369

xep-0405.xml
Make Archiving Optional
Bump Namespace
=> Mix PAM - XEP-0405

xep-0277.xml
=> XEP-0277: Fix typos/wording

inbox/reactions.xml
> This specification defines a way for adding reactions to a message.
=> ProtoXEP: Message Reactions

xep-0060.xml
This feature is similar to 'muc#roomconfig_publicroom' but applied to Pubsub nodes.
=> XEP-0060: Add pubsub#public in Publish-Subscribe features

xep-0364.xml
Let me know if I should also add a new revision entry.
=> XEP-0364: Fix link to Daniels article

inbox/cs-2020.xml
There is a new section "Future Development" that's up for discussion.
=> Forked XEP-0412 into Compliance Suite 2020

xep-0084.xml
Related Mailing List Posting: https://mail.jabber.org/pipermail/standards/2019-August/036376.html
=> XEP-0084: Bump bytes datatype from unsignedShort to unsignedInteger

xep-0405.xml
=> XEP-0405: Reference latest core (core:1);

xep-0392.xml
Those are out of scope for the XSF. This also constitutes the
release of version 0.7.0.
Rendered version here: https://sotecware.net/files/xeps/xep-0392.html
=> XEP-0392: Remove all UX/UI recommendations

xep-0420.xml
This PR introduces IQ encryption workflow and adds missing explanation and examples.
=> XEP-0420: Version 0.2

xep-0423.xml
This is a set of changes to CS-2020 resulting from the Last Call feedback.
=> XEP-0423: Last Call feedback

inbox/charcount.xml
Rendered version: https://dino.im/xeps/charcount.html
=> Add ProtoXEP: Character counting in message bodies

xep-0426.xml
Rendered: https://dino.im/xeps/xep-0426.html
HTML diff: https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fxmpp.org%2Fextensions%2Fxep-0426.html&doc2=https%3A%2F%2Fdino.im%2Fxeps%2Fxep-0426.html
=> charcount 0.2: Include feedback/clarifications from list

xep-0401.xml
This reverts commit 5f43884d3a2f3356a1723f9b3afe8c466d64bf58.
It was incorrectly merged.
=> Revert "XEP-0401: update pre-authenticated IBR"

xep.ent
Forward Health -> Pando rebranding.
Hopefully the last time for a while!
=> Update Dave Cridland email address

xep-0412.xml, xep.xsl
Also fix the truncated header message.
=> Obsolete CS-2019

xep-0430.xml
Updates to Inbox (XEP-0430) to address issues raised in the Summit.
=> XEP-0430 Inbox Summit 24 Updates

inbox/udt.xml
Resubmission trying a less ambitious attempt.
=> ProtoXEP: Resubmit UDT as Simple JSON Messaging

xep-0369.xml
This PR fixes some things I came across while reading it.
=> XEP-0369: Fix MIX typos, indentation, wording

xep-0428.xml
Fix missing closing of <subject/> element.
=> XEP-0428: close <subject/>

xep-0384.xml
=> XEP-0384: OMEMO Encryption

inbox/password-storage.xml
This proto XEP provides best practices for password hashing and storage, tuning PBKDF2, and selecting SASL mechanisms. It will likely need expert review.
**Rendered:** https://blog.samwhited.com/xeps/inbox/password-storage.html
=> Proto XEP: "Best practices for password hashing and storage"

xep-0411.xml
It seems there were a few copy/paste mistakes.
=> XEP-0411: Fix (typo) XEP numbers

xep-0402.xml
=> XEP-0402: Fix closing tags in examples

xep-0402.xml
=> XEP-0402: Add schema

xep-0389.xml
Overhauls the structure of the document to make it easier to follow.
This revision also adds more information to the success element to support flows where the server sets the final JID.
=> XEP-0389 readability overhaul

xep-0393.xml
Simple clarifications and terminology fixes based on LC feedback for XEP-0393.
=> XEP-0393: editorial changes from LC feedback

xep-0393.xml
Resubmitting with registrar updates, a disco feature, and the zero width space technique.
=> XEP-0393: updates based on LC feedback

xep-0402.xml
=> XEP-0402: schema: <extensions/> is optional

xep-0424.xml
And add another disco URN for tombstones.
Discussion on standards list: https://mail.jabber.org/pipermail/standards/2020-May/037327.html
=> XEP-0424: Clarify when a service must advertise disco support

xep-0384.xml
Incorporate some feedback Sofía gave [on the mailing list](https://mail.jabber.org/pipermail/standards/2020-May/037382.html).
=> XEP-0384: Incorporate feedback from Sofía Celi

xep-0157.xml
https://mail.jabber.org/pipermail/standards/2020-May/037443.html
=> XEP-0157: Add status-addresses registrar entry

xep-0420.xml
Changelog in the revision block
=> XEP-0420: Revision 0.3.0

xep-0313.xml
PR 3 of 3 for XEP-0313 0.7
Due to the well-established nature of this protocol at this point in time, I will be seeking feedback on list before considering this PR ok to merge.
=> XEP-0313: new revision 0.7

xep-0313.xml
perhaps missed during copy/paste from similar note further below
=> XEP-0313: Correct MAM UID "not-found" note

inbox/xep-mam-prefs.xml
PR 1 of 3 for XEP-0313 0.7
This is the preferences protocol, split out into a separate document per community consensus.
=> New protoXEP: MAM Preferences

inbox/cs-2021.xml
It's time to start working on next year's good new thing.
@iNPUTmice promised to add a section about A/V, so please don't merge this PR yet until that section is added.
=> Draft: Compliance Suite 2021: copied from XEP-423

xep-0438.xml
Updates to match [draft-ietf-kitten-password-storage-01](https://datatracker.ietf.org/doc/draft-ietf-kitten-password-storage/).
=> XEP-0438: update to match draft-ietf-kitten-password-storage-01

prettify.css, xmpp.css
Fixes #1009.
Thanks Zash for the idea!
=> Add a dark theme for the XEPs

xmpp.css
=> Invert colors of info boxes in dark mode

inbox/automatic-trust-management.xml
This should be merged after #1003.
=> ProtoXEP: Automatic Trust Management (ATM)

inbox/muc-mention-notifications.xml
The XEP can be read here:
https://conversejs.org/xeps/inbox/muc-mention-notifications.html
=> Inbox: add new protoXEP: MUC Mention Notifications

inbox/doap-usage-in-xmpp.xml
This specification defines how XMPP projects can provide a machine-readable description of their abilities, and how external entities can interact with it.
=> ProtoXEP: DOAP usage in XMPP

xep-0402.xml
Otherwise links can die, like in https://docs.modernxmpp.org/client/groupchat/#bookmarks
=> XEP-0402: Add stable anchors to all relevant sections

tools/2xep.lua, tools/md-diff.sh, tools/xep2md.lua, tools/xep2md.sh
```bash
xmllint --nonet --noent --loaddtd xep-0313.xml | lua > xep-0313.md
```
Requires [luaexpat](https://matthewwild.co.uk/projects/luaexpat/).
```bash
pandoc xep-0313.md -t tools/2xep.lua
```
Requires [pandoc](https://pandoc.org/).
=> Add tooling for conversion to/from Markdown

xep-0313.xml
Fix an outstanding TODO and add a registrar considerations section.
=> XEP-0313: remove "FIXME" comment

tools/2xep.lua
Based on feedback from @horazont
=> Markdown tooling tweaks

xep-0280.xml
As voted in Council today, https://logs.xmpp.org/council/2021-03-17#2021-03-17-8aae2c6dbeddfaf5
=> XEP-0280: take over XEP maintenance

xep-0434.xml
Add new section, use more precise sentences, apply consistent formatting:
* Add new section for Trust Message URIs
* Use 'that' instead of 'which' for restrictive clauses
* Apply consistent formatting for paragraphs and revision history
=> XEP-0434: Release version 0.4.0

xep-0434.xml
Update to XEP-0450 version 0.3.0 and apply consistent formatting:
* Update ATM's namespace to 'urn:xmpp:atm:1'
* Apply consistent formatting for revision history
=> XEP-0434: Release version 0.5.1

inbox/moved2.xml
Note: This may become an update to XEP-0283 pending authorship reassignment.
=> ProtoXEP: Moved 2.0

prettify.css, xmpp.css
This was reported by this tool: https://wave.webaim.org/
=> CSS: Improve the contrast for the dark theme

xep-0450.xml
=> XEP-0450: Release version 0.3.2

xep-0458.xml
I've tried to take in the comments (boht public and private) and
process them objectively.
This is unlikely to have been as objective as anyone will have
wanted, of course.
=> XEP-0458 Code of Conduct comments

xep-0383.xml, xep.ent
Rewrite parts of 0383 to include listing JIDs and to improve the security considerations and registrar considerations sections.
=> XEP-0383: add listing of JIDs

xep-0413.xml
I forgot to change the status after Experimental
=> XEP-0413: update status to Experimental after 0.2 changes

xep-0429.xml
=> XEP-0429: Add discussion venues

xep-0082.xml
privcacy -> privacy
a ISO -> an ISO
=> XEP-0082: Small orthographic corrections

xep-0215.xml
Looks like a copypaste typo of some sort.
=> XEP-0215: Fix wrong 'type' on response

xep-0227.xml
- Discourage inclusion of plaintext passwords
- Document a format for including SCRAM data
- Define data formats for PEP and MAM data
=> XEP-0227: New revision 1.1

xep-0413.xml
The date mistake was bothering my OCD since July. :) I hope it's okay to rewrite history just a bit.
=> XEP-0413: fix a temporal typo in revision history

xep-0280.xml
This PR contains multiple changes based on the 2019, 2020 and 2021 Last Calls.
There is one controversial change that probably requires a Council vote.
=> XEP-0280: feedback from Last Calls

xep-0459.xml
Incorporate feedback from last call.
https://mail.jabber.org/pipermail/standards/2021-October/038628.html
=> XEP-0459: Incorporate feedback from last call

xep-0045.xml
=> XEP-0045 - Fix typo missed in rev. 1.25

xep-0420.xml
Clarify bare JID usage and improve sentences:
* Clarify usage of bare JIDs for affix elements
* Improve and correct sentences about affix elements
=> XEP-0420: Release version 0.4.1

xep-0380.xml
Add new OMEMO namespaces:
* Add 'urn:xmpp:omemo:1' for OMEMO versions since 0.4.0
* Add 'urn:xmpp:omemo:2' for OMEMO versions since 0.8.0
=> XEP-0380: Release version 0.4.0

xep-0280.xml
=> XEP-0280: Fix indentation in examples

inbox/pubsub-ns.xml
Introduce a new XEP called Pubsub Namespaces
Fix #986
=> Inbox: Pubsub-ns first draft

prettify.css
Make it Mauve instead of purple.
=> CSS: improve the contrast of DTD in the dark theme

xep-0313.xml
=> XEP-0313: Fix inconsistency and indentation

xep-0163.xml
=> XEP-0163: Release version 1.2.2

xep-0072.xml, xep-0096.xml, xep-0214.xml
Thread at https://mail.jabber.org/pipermail/standards/2022-March/038784.html
=> XEP-0072, XEP-0096, XEP-0214: fix xmlns in sipub examples

inbox/ephemeral-messages.xml
Reopening the discussion about ephemeral messages.
Rendered version: https://bouah.net/specs/ephemeral-messages.html
Should I try to contact the original author to take over the name? I added a 0.0.2 version to keep track of the original document.
Technically this spec isn't complete and I'm hoping to get feedback by submitting it, even though I would have preferred to get it before.
=> Ephemeral messages -- Take 2

xep-0432.xml, xep-0462.xml, xep.ent
=> XEP-0462: various fixes

inbox/bookmark-pinning.xml
This extention allow users to pin XEP-0402 Bookmarks
Re-submitting from a custom branch
=> ProtoXEP: Bookmark Pinning

inbox/pubsub-attachments.xml
This specification provides a way to attach elements to a pubsub item.
=> Add ProtoXEP: Pubsub Attachments

xep-0465.xml
Update Security Considerations according to council feedback.
=> XEP-0465: version 0.1.1

xep-0447.xml
Add disposition attribute to signal when inlining is desired.
=> XEP-0447: Stateless File Sharing v0.2.0

xep-0453.xml
=> Fix link, broken with the xmpp.org move to Hugo

xep-0446.xml
Use height/width instead of dimensions
=> XEP-0446: File Metadata v0.2.0

xep-0293.xml
Fix attribute name of 'parameter' element as specified by XML schema
=> XEP-0293: Release version 1.0.2

xep-0353.xml, xep.ent
=> Add author entity for tmolitor

xep-0440.xml
as discussed with @Flowdalic in the XSF muc
Rendered version: https://gultsch.de/files/xep-0440.html
=> XEP-0440 - make channel-binding a top level stream feature

inbox/events.xml
This specification describe how to handle events with XMPP.
=> Add ProtoXEP: Events

inbox/pubsub-social-feed.xml
This specification defines a way of publishing social content over XMPP.
=> ProtoXEP: Pubsub Social Feed

inbox/pubsub-signing.xml
Specifies a mechanism to sign pubsub items
=> Add ProtoXEP: Pubsub Signing

inbox/pubsub-signing-openpgp.xml
Specifies a pubsub signing profile for OpenPGP
=> Add ProtoXEP: Pubsub Signing: OpenPGP Profile

inbox/pubsub-targeted-encryption.xml
Specifies a way to encrypt pubsub items for a restricted set of entities
=> Add ProtoXEP: Pubsub Targeted Encryption

xep-fast.xml
Note: Depends on XEP-0388 changes introduced in #1214. Nevertheless, I'm submitting this PR to get it out into the open so people have the opportunity to read and review the proposal.
=> New ProtoXEP: Fast Authentication Streamlining Tokens

xep-0045.xml
=> XEP-0045: Remove more of GC1

xep-0167.xml
Specify attribute 'name' of 'mute' and 'unmute' elements as optional in schema
=> XEP-0167: Release version 1.2.2

.github/workflows/xep-validation.yml
Adds a Github workflow that executes `tools/validate-xep0001-conformance.sh` against any changed XEP that was changed in a pull request.
=> #1240 Integrate XEP validation in Continuous Integration

xep-0472.xml
- Change the specified pubsub#type profiles to be more consistent
- Rephrase some paragraphs
- Fix examples formating
=> Update XEP-0472 Pubsub Social Feed to 0.1.1

inbox/cs-2023.xml
No changes after a first inspection of the CS 2022.
=> Compliance Suite 2023: copied from XEP-0459

xep-0474.xml
This simply does what the title says.
=> XEP-0474: Describe the attack models mitigated by SSDP and IETF interaction

xep-0444.xml
=> XEP-0444: Add the XML Schema

xep-0426.xml
Added section about subsequences.
=> XEP-0426: Character Counting 0.3.0

xep-0353.xml
Exactly what the title says.
See the discussion in the XSF MUC and on the standards@ list (thread: "JMI rollback").
=> Port version 0.5 to :0 namespace and introduce <ringing/>

inbox/xep-scram-upgrade.xml
Current rendering: https://dyn.eightysoft.de/final/xep-scram-upgrade.html#protocol
=> Overhaul SCRAM Upgrade ProtoXEP to include definition of SASL2 upgrade tasks

xep-0472.xml
- Change the pubsub#type to be consistent with other XEPs such as XEP-0372
- Add a Discovery section
=> XEP-0472: Pubsub Social Feed, cleaner pubsub#type, discovery section

inbox/muc-token-invite.xml
Rendered version: https://bouah.net/specs/muc-token-invite.html
=> ProtoXEP: MUC Token Invite

xep-0458.xml
This makes it much easier to link to a particular section, so we already know by reading the link which section it refers to.
Edit: also fix a typo.
=> XEP-0458: Add anchors to each section

xep-0424.xml
Most recent discussion here: https://mail.jabber.org/pipermail/standards/2023-February/039164.html
CC @iNPUTmice
=> XEP-0424: Remove dependency on XEP-0422 'Message Fastening'

xep-0377.xml
This has been tested with xmllint against every example in the XEP.
=> XEP-0377: Add the XML Schema

xep-0458.xml
Please do not merge this until @dwd and @stpeter agree on the changes.
=> XEP-0458 Last Call feedback

xep-0045.xml
The spec everywhere else specifies it should be called roomconfig_changesubject and this is also present in this example as well lower down.
=> roominfo_changesubject does not exist

Dockerfile, Makefile
=> Revert "Add license for bibliographic data (second attempt)"

inbox/xep-mds.xml
Rendered XEP: https://gultsch.de/files/xep-mds.html
=> add XEP for 'Message Displayed Synchronization'

xep-0398.xml
add security considerations for both methods
=> XEP-0398: explain copy vs inject on access

xep-0333.xml
Rendered version: https://gultsch.de/files/xep-0333.html
=> XEP-0333: Display Markers. Remove received and ack

xep-0388.xml
Rendered: https://gultsch.de/files/xep-0388.html
=> XEP-0388: add missing elements to XML Schema

inbox/av_conferences.xml
This specification defines a way to hold multiparty conferences with an SFU via Jingle.
=> Add ProtoXEP: Jingle Audio/Video Conferences

xep-0474.xml
=>  XEP-0474: Fix typos and adapt attack-model section to new simplified protocol

xep-0114.xml
=> XEP-0114: Add missing 'approver' element.

xep-0126.xml
=> XEP-0126: Add missing 'approver' element.

xep-0188.xml
=> XEP-0188: Add missing 'approver' element.

xep-0190.xml
=> XEP-0190: Add missing 'approver' element.

xep-0205.xml
=> XEP-0205: Add missing 'approver' element.

xep-0485.xml
I'm not sure if this requires a revision block.
=> XEP-0485: Fix external entity declaration.

tools/extract-metadata.py
=> tools: Add '<supersedes>' and '<supersededby>' elements to xeplist.xml

xep-0453.xml
There is absolutely no change to the resulting document, but if I ever changed my name or contact addresses it would be easier to do so in one place.
=> XEP-0453: Replace my author block with the entity

xep-0474.xml
=> XEP-0474: Use better value delimiter

xep-0480.xml
=> XEP-0480: Fix SCRAM upgrade description and XML schema

.github/workflows/xep-validation.yml
Update tj-actions/changed-files to v46 (this version updated internal dependencies).
Note: This action recently had [security issues](https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised). These issues have been fixed in the version we're currently using. Action logs did not reveal any secrets.
=> ci: XEP validation: Update GitHub action for changed files

xep-0388.xml
kind of nitpicking, but well, that's the point of xml schemas
=> XEP-0388: XML schema: Add missing minOccurs=0 to additional-data

xep-0363.xml
Rendered: https://conversations.im/xep-0363.html#purpose
=> XEP-0363: specify purpose/buckets when requesting slots

inbox/pubsub-filter.xml, inbox/pubsub-ns.xml, inbox/pubsub-social-feed.xml, inbox/stories.xml, xep-0330.xml, xep-0472.xml, xep-0501.xml
Everything is in the title, just a simple XML cleanup XEP
=> Replace edhelas <author> with the related entity
