xsf/xeps

- xep.xsl
Valuable for when a XEP is currently under consideration by XMPP Council, especially if one or more Council members voted -1 until author addresses issues.
> Exclude note on when last call ends if no <lastcall> 

- .gitignore
Ensures that binary files generated by Python, and other temp files that we may end up with in the repo are ignored by Git.
Comprises two gitignore files taken from [this collection](https://github.com/github/gitignore).
> Gitignore pyc and other temp files

- xep.xsl
Fix the source control link in Appexndix A of all XEPs which is currently pointing to Gitorious (which no longer exists).
> Fix source control link in XEPs

- xep-0016.xml
Although lost to the annals of time now, very likely the &lt;schemaloc&gt; was removed when XEP-0016 transitioned from:
1. **Draft** to **Deprecated** (because draft-ietf-xmpp-im included iq:privacy)
2. **Deprecated** to **Retracted** (because RFC 3921 included iq:privacy)
3. **Retracted** to **Draft** (because RFC 6121 removed iq:privacy)
This change is simply adding (back?) the publication pointer for consistency with other XEPs.
> add pointer to published schema

- xep-0313.xml
The MAM history already says "Switch the sentinel message back to the iq
result.", but this has never happened. This commit does the switch.
This hasn't been done in 6 months. I really like to proceed MAM forwards, and remove the sentinel, [which I consider to be a design flaw](http://mail.jabber.org/pipermail/standards/2015-January/029514.html)
The commit itself is best viewed as word diff: `git show f46e5d --word-diff`.
Summoning @mwild1 and @Kev for review.
> Remove message sentinel from MAM (XEP-0313)

- xep-0174.xml
We are currently in the process of adding xep174 support to Smack and found that most (all?) already existing implementations send `<?xml ...>` before the opening stream element. This is not shown in the examples or stated in the text, unlinke rfc6120 where every example has them.
> Add '<?xml ...>' to XEP-174 examples

- xep-0264.xml
- Changes name to "Jingle Content Thumbnails", as these can be used outside of file transfer
- Updates format of `<thumbnail />` to use a 'uri' attribute to allow HTTP URIs and not just BoB
- Updates examples to latest protocol formats
- Bumps namespace version
> Update XEP-0264 to allow non-cid URIs, and expand scope

- inbox/otrdisco.xml
Update the security section of OTR Disco to fix an outdated statement that doesn't make sense with the current version of the XEP.
> Update OTR Disco's security section

- inbox/entityversioning.xml
Fix a minor escaping issue which was just pointed out. This change is purely editorial.
> Fix escaping in entity versioning cdata

- xep-0359.xml
Single word (completely editorial) typo fix for EP-0359.
s/as/a/
> Fix a small typo on XEP-0359

- xep-0320.xml
based on LC feedback from @stpeter this clarifies that holdconn is not used/defined.
Also adds reference to 0343
> XEP-0320: clarify that holdconn is not used

- inbox/entityversioning.xml
Initial draft of the final part of the entity versioning spec. This adds a "search" or "auto complete" IQ which can be used for finding items when only a partial representation of a list is known.
Eg. if only a few users out of the entire roster are known, one can use the IQ (along with matches from the local set) to fill in an auto complete list that is shown when the uesr attempts to start a conversation, or to fill out the list when the user performs a search over the roster.
With this addition to the EV spec it has reached feature completion as it was originally envisioned. Futher discussion on the mailing list / consideration by the council can now commence.
> Entity Versioning Search Endpoint

- Makefile
Uses inotifywatch to generate an HTML file anytime an XML file is saved.
This probably won't work on OS X, but it would be easy enough to use `fswatch` if someone that actually has a machine running it wants to tweak it to fallback to fsswatch if inotifywait doesn't exist.
> Add `make preview' to generate HTML on XML save

- Makefile
It leaves a lot of the other html steps.  Didn't want to cause too much surprise up front, and they can be further collapsed later.
> remove PDF build steps from Makefile (fixes #121)

- xep-0370.xml
XEP-0370 is experimental, not a protoxep (it's already been accepted by the council and assigned a number)
> XEP-0370: Mark as experimental

- xep-0364.xml
Updated to include information about establishing and tearing down an OTR session, and how to handle delivery receipts.
I've also removed RFC 2119 language except for RECOMMENDED and NOT RECOMMENDED as this is an informational document.
Further discussion on the mailing list ([April thread](http://mail.jabber.org/pipermail/standards/2016-April/031034.html), [May thread](http://mail.jabber.org/pipermail/standards/2016-May/031058.html)) is welcome.
> XEP-0364 Session and delivery receipts updates

- xep-0376.xml
This was approved by the council, but appears to have fallen off the radar.
> XEP-0376: Assign to Pubsub Account Management

- xep-0358.xml
In order to allow users to share files via XMPP URIs, Jingle and XEP-0358. But this is not only limited to file sharing, e.g. links Audio/Video conferences could be shared too.
If this get's the accepted, then the registry should be updated to. But http://xmpp.org/registrar/querytypes.html is currently a 404 and I've no idea where the registry is maintained.
> Add 'jingle' XMPP URI querytype to XEP-0358

- xep-0156.xml
Not sure what the procedure on editorial fixes to Draft XEPs is, but I'm pretty sure the encoding here should be UTF-8, not UTF-9.
> XEP-0156: Fix typo (s/utf-9/utf-8/)

- README.md
The "submitting a xep" link was broken, and move what’s possible to HTTPS.
> Update the links in the readme

- xep-0167.xml
Thanks to Konstantin Kozlov for reporting this in
http://mail.jabber.org/pipermail/standards/2016-June/031166.html
> Fix typo in XEP-0167: s/PMCA/PCMA/

- xep-0373.xml
Items returned from a pubsub items request are encapsulated in an
<items/> element, not <publish/>, which is used for publishing items.
Example for requesting the secret key was labelled as requesting the
public key.
> Fix some copypasta problems.

- xep-0156.xml
- xep.ent
Add a business rule clarifying that the XML version of the host-meta file in XRD format is REQUIRED, while the JSON version is OPTIONAL.
This is already specified by the RFC, but for clarity it's worth stating here too.
Also update references to the draft version of the websockets subprotocol to point to RFC 7395.
This change is editorial in nature.
> XEP-0156: The XRD host-meta file is REQUIRED and the websocket subprotocol is now RFC 7395

- xep-0313.xml
Also fix wrong usage of MESSAGE to IQ, fix example 9 and clarify where
the 'complete' attribute is placed.
Should address all issues raised in http://mail.jabber.org/pipermail/standards/2015-December/030730.html
> XEP-0313: Actually mention <fin/> in text

- xep-0191.xml
Clarify that arbitrary JIDs (not just contacts) may be blocked with the blocking command. This matches real world usage of the spec.
I've done a minor version bump because this is backwards compatible, but does (possibly) introduce new functionality (even if most [all?] servers are already doing this).
> XEP-0191: Allow blocking arbitrary JIDs

- xep-0234.xml
ICE-TCP is RFC 6544. RFC 6455 is an important too and authored by someone familiar but not related to filetransfers ;-)
> xep-0234: update wrong reference to ice-tcp

- xep-0375.xml
Adds a footnote to indicate that web clients don't need to implement BOSH and Websockets. It should be an OR.
> XEP-0375: Webclients don't need BOSH and websockets

- prettify.css
- xmpp.css
This change unifiess the rendering for &lt;example> and &lt;div class=example>.
The former is rendered as HTML &lt;pre>, the latter is taken over. This
patch does the following:
* Merge &lt;pre> CSS from prettify.js int xmpp.css
* Give &lt;pre> a blue-ish background derived from the caption color
* Make the &lt;pre> border use the caption color
* Change div.example background color from neon yellow to a colder and lighter tone that matches the overall color theme
* Add a border to div.example that fits its background color
* Derive width for div.example from &lt;pre>
Side-by-side comparison:
http://xmpp.org/extensions/xep-0071.html#examples
https://op-co.de/tmp/xep-0071.html#examples
There is also an xmpp.css in the xmpp.org repo. I'm not sure what it is used for and how this change would …
> Improve rendering of <example> and div.example HTML

- xep.dtd
Adds a few obvious missing allowed children to various elements in the
DTD.  Before this, 277 XEPs failed to validate, after the change, 'only'
179 fail to validate. It also means a portion of those XEPs contain
things that will never be converted to HTML or PDF, because our XSLT
doesn't know about them.
Tested the DTD against our current body of XEPs using xmllint 2.9.1.
> Fix obvious mistakes in the DTD

- xep-0369.xml
Revision 0.2.1 of xep-0369.xml had two <initials/> and two <remark/>
elements, both of which are illegal. Merged them, as I think it's the
least ungraceful recovery from the dual 0.2.1 revision issue.
xep-0369.xml now validates according to the DTD using xmllint.
> XEP-0369: Fix revision 0.2.1 XML

- xep.xsl
XSLT processors are allowed to choose either the self-closing form or
explicit open and close tags when operating in xml mode for elements
that have no text.  Unfortunately, for the script element, this is not
allowed (by the DTD, and conformant browsers will not accept the
self-closing form).
xsltproc, as used by the XSF tooling, will output the open/close tags,
but other processors, such as Xalan, will choose the self-closing form.
This patch adds an empty comment as a child of the script tag. This will
force all XSLT processors into outputting the right form. As browsers
are required to ignore the content if there is a src attribute, this
will not change the behaviour. Should a browser without support for the
script tag open it, all it sees is a comment.
Transforms …
> xep.xsl: Force open and close tags on script

- xep-0369.xml
* Fix examples that do not follow the proxy JID format as specified in section 3.5 and other small typo fixes.
* Change instances of "presence message" to "presence stanza" (a message is a thing in XMPP land so "presence message" doesn't make a lot of sense and is confusing)
* "UUID unique ID" is redundant; remove the "unique ID"
/cc @stevekille @Kev @stpeter
> XEP-0369: Minor formatting and grammar fixes

- xep-0369.xml
Nit pick: The definition of the map node is somewhat circular. This tweaks the language to remove the circular definition using a synonym.
/cc @stevekille @Kev @stpeter
> XEP-0369: Remove circular definition

- announce.py
- xep-README.xml
This prevents the editor from having to think about the correct URL.
> Automatically generate the diff URL from the previous and current version for announce

- xep-0037.xml
~~This commit explicitly doesn’t create a new version, since this XEP is
already rejected.~~
> XEP-0037: Fix double “Version” in revision history

- checkdeadlinks.py
Main user-visible changes are:
- It’s now usable in a script, just check for exit status (1 contains dead links, 0 none), and get a list of dead links on its stdout.
- Python 3.x compatible.
- Also checks for image sources.
> Improve checkdeadlinks.py

- xep-0329.xml
This:
- removes ugly whitespace around examples
- makes indentation consistent
- makes every example look correct
- updates JingleFT dependency to 0.16+ (:4 namespace).
> XEP-0329: update to JingleFT:4 and various cosmetic fixes

- inbox/eme.xml
- Made the 'name' attribute optional for existing mechanisms.
- Added a remark about the possibility to hide encrypted messages
following user input.
- Made explicit that this protocol affects any encryption mechanism,
present or future, not only those listed here.
- Display the namespace of the encryption mechanism in the default
messages.
> Explicit Message Encryption ProtoXEP: Add a 0.0.2 version

- xep.xsl
Using single quotes around the namespace.
> xep.xsl: Improve the schemaloc > ns sentence

- xep-0363.xml
The reference to the TLS rfc is wrong this commit fixes that.
> Fix tls reference in http upload xep

- inbox/burner.xml
Change burner JIDs to use a new session where they are the authorization identity.
/cc @fippo
> Start addressing burner JID feedback from Fippo

- xep-0045.xml
I think this sentence is confusing.
A moderator cannot be a participant at the same time, because it can only have one role.
I think the context is referring to an affiliation here, which should be "member" or "member or admin".
> XEP-0045: participant should be member

- xep-0369.xml
Remove lots of random EOL whitespace and tabs in XEP-0369 before publishing 0.5. Waiting on Travis before merge.
> XEP-0369: Remove lots of whitespace errors

- xep-0053.xml
I'm not sure if this is desirable or not, but I noticed a lot of registry entries have "(DEPRECATED)" at the end of their name or description. This adds deprecated as an official status which could work in the same way xsf/registrar#12 adds the proposed status, giving us a consitsent way to mark registry entry status'.
> XEP-0053: Add deprecated status

- .travis.yml
- Makefile
This runs `xmllint` against all XEPs, but only fails the build if *new* issues were introduced (to prevent all builds failing until the ~4000 something existing issues are fixed).
Currently fixes to existing issues require that the number of open problems be manually updated, this can be done by installing [git-ratchet](https://github.com/iangrunert/git-ratchet) and then doing something like this:
```sh
echo "lint,$(xmllint --nonet --noout --noent --loaddtd --valid *.xml 2>&1 | wc -l)" | git-ratchet check -v -w
git push https://github.com/xsf/registrar.git refs/notes/*:refs/notes/*
```
(or replace the URL with `upstream` or `origin` or whatever points to the xsf version of this repo for you)
CI could also update this when you merge to master, but I don't have access to create a deploy key …
> Add ratcheting DTD checking to CI

- xep-0050.xml
- xep-0055.xml
Fix issues with XEP-0050's schema (https://trello.com/c/6PHfEitZ/139-xep-0050-inconsistency) and clean up some whitespace and DTD issues as well, one of which also occured in 0055.
> XEP-0050, XEP-0055: Schema, DTD, and whitespace

- Makefile
This will fail until #301 is merged and is blocking.
*EDIT: 2016–12–03*: Unblocked
> Check for external resources in CI

- xep-0363.xml
- xep-0369.xml
Fix typos in XEP-0363 and XEP-0369.
This commit originally had a schema for 0363 when the author submitted it, but it appears to have been copy/pasted from another spec and was not actually relavant for 0363 so I have removed it.
> XEP-0363, 0369: typo fixes

- xep.xsl
I was just copy/pasting and tweaking XSLT from StackOverflow, so someone who has any idea how this generate id stuff works should probably review this.
This also needs to be done for the PDFs probably, but this can be a separate PR.
We probably also want a way to cite a footnote from something that has different text than the footnote (eg. `&xmppcore;` and `<cite>XMPP Core</cite>` and `<cite>RFC 6120</cite>` should point to the same thing); this can also come later.
> Don't duplicate footnotes in HTML

- xep.xsl
Tested on a single XEP that it works as expected. Repeated
notes get the same note number and the notes section only
mentions each note once.
> Remove duplicates from ‘Notes’ section in XHTML rendered XEPs

- xep-0033.xml
- A stanza can contain multiple replyto and replyroom items (as per §
4.6.4), make it clear in the reply handling section as well.
- Fix examples. Include the BCC address in the addresses element, when the
stanza is sent to the BCC addressee.
This is as per the sentence ' Each 'bcc' recipient MUST receive only the
<address type='bcc'/> associated with that addressee.'
- Include 'ofrom' attribute as defined in XEP-0045.
> XEP-0033: Clarify Reply Handling, add 'ofrom' type and fix examples

- xep-0144.xml
I'm not sure this is strictly required, but it's nice to keep things consistent.
> XEP-0144: Make date field a valid date

- xep-0119.xml
- xep-0161.xml
- xep-0270.xml
- xep-0281.xml
- xep-0289.xml
- xep.xsl
This makes it way more explicit when a XEP has been superseded by some other specification(s), while leaving the same current list in Appendix A.
This will require all of the HTML files to be rebuilt once it gets merged.
> List the supersededby in the abstract

- xep-0045.xml
This is a purely cosmetic change, so no version bump.
> XEP-0045: Remove trailing whitespace in examples

- xep-0369.xml
Ensure all RFC 2119 keywords are capitalized and used correctly;
Use MAM ID to identify message;
Clarify use of the various channel names;
Require all client operations to be direct or indirect (choice is just confusing);
Add description of implicit activation ;
MIX Domains must not contain users;
Clarification on identifying channels in rosters;
> MIX (XEP-0369) version update to 0.7.1

- xep-0234.xml
The Council determined that the namespace version bump in XEP-0300 necessitated a corresponding version bump in XEP-0234.
> XEP-0234 Update to new version of XEP-0300

- xep-0368.xml
The only thing I'm not sure of is where the comments re: RFC 2595 belong @dwd I put them in IANA Considerations, but that somehow feels wrong, any thoughts?
> Implement initial last call comments for XEP-0368, editorial changes, SNI is now MUST

- xep-0387.xml
* Adds direct MUC invitations to the group chat feature (for a good chat experience, we should ensure everyone can receive invitations, even people blocking traffic from non-contacts)
* Add a section for chat states that is only required for advanced client.
* Add direct TLS SRV records (and a footnote clarifying what it means to support TLS SRV records for servers)
* Typo fix (thanks @ge0rg!)
> XEP-0387: Add several missing XEPs / typo fixes

- xep-0369.xml
Update after Brussels Summit;
Remove Explicit Client Activation and replace with client capability discovery (summit 3);
Limit Indirect to Join/Leave;
Clarify Server use of Disco of Client;
Add MIX capability information to Roster (summit 10);
MIX as Core Spec (summit 1);
Clarifications of password control, voice and name/description (summit 4/5/6)
Removal of Subject and reference future Sticky Messages XEP (summit 7);
Use example JIDs aligned to anticipated BIND2 specification;
Clarify PubSub Node Type;
Add Error handling section;
Substantial Editorial Review;
> Mix  - XEP-0369 to 0.8

- inbox/ibr2.xml
Simplify the stream features listing a bit; while playing with an implementation to see how it worked, the list format and ability to act as auth made things a bit tricky for no immediate benefit. Also giving the option to not to SASL feels like it could go badly wrong somehow.
An example of listing / parsing features and an experimental API can be found here: https://godoc.org/mellium.im/xmpp/ibr2 (actual negotiation is not yet complete).
> ibr2: Simplify the stream features listing

- xep-0280.xml
In light of [CVE-2017-5589+ Multiple XMPP Clients User Impersonation Vulnerability](https://rt-solutions.de/en/2017/02/CVE-2017-5589_xmpp_carbons/) and after a chat with @ge0rg I came to the conclusion that similar mishaps can be avoided by improving readability of the requirements.
This PR is a proposal for restructuring the XEP so that each single requirement can be easily discerned from other requirements, i.e. each structural element does not contain more than one requirement (so you can check them each and cross them off the list), while still keeping overall readability as a document.
There are no changes to the actual content. I only moved some things around within a section, e.g. single short paragraphs after a screen full of examples, which could be easily overlooked. Here and …
> XEP-280: Improve readability

- xep-0233.xml
Clarified to avoid reliance on insecure DNS queries for determination of hostname
> Clarification

- inbox/ecaps2.xml
As discussed, Entity Capabilities could use an overhaul.
This is a proposal for an entirely new XEP superseding XEP-0115, while providing a transition plan for entities and allowing both to co-exist.
This is my first ProtoXEP. Please let me know if I made any non-trivial mistake, especially related to formalities and acknowledgements of prior art. I am a bit worried about the little acknowledgement the original authors of XEP-0115 get here, as well as the various discussions which happened on the mailing lists with respect to the issues of XEP-0115, but I’m unsure how to handle this better.
> ProtoXEP: Entity Capabilities 2.0

- inbox/ecaps2.xml
* issueing -> issuing
* was -> were (subjunctive mood)
* Add commas around subordinate clause "per XMPP Core"
* Make "for example to increase the privacy" a parenthetical, remove word "the".
* "ordering of children in disco#info... elements does, however, not matter" -> "elements, however, does not matter"
> XEP-xxxx: Entity Capabilities 2.0: Spelling/grammar change

- xep-README.xml
The http://xmpp.org/protocols/ page doesn't appear to exist anymore; I'm assuming it's similar to https://xmpp.org/extensions/index.html which is auto updated.
> README: Remove invalid step from advancing section

- Makefile
LaTeX sometimes requires multiple passes to build external files; make sure the ToC compiles by guessing if we need another pass based on log output.
> make: Rerun xelatex to build ToC in PDFs

- Dockerfile
- Makefile
- README.md
Runs, http://localhost:3080/extensions/xep-0001.html serves styled
content.
> Add Dockerfile serving HTML extensions

- xep-0363.xml
example had a </request> closing tag that didn't belong there
> XEP-0363: fixed typo in example 5

- xep-0390.xml
Now that it’s experimental, here come the minor changes I had in the pipeline.
* Some editing
* Explicitly mention the possible need for rate-limiting of caps processing in Security Considerations
* Reference UTF-8 and Base64 RFCs
* Reference U+002E properly
> ecaps2 (XEP-0390) to version 0.1

- Dockerfile
- Dockerfile.base
- Create a `Dockerfile.base` that contains all the dependencies and required directory structure
**that image will need to be published to the hub** (as xmppxsf/xeps-base currently)
- Put minimal content into the `Dockerfile` and allow the number of make jobs and the make targets to be parametrized through docker build arguments.
This should, once someone publishes the base image to the hub, cut the full build time in half or more (because the old dockerfile was mixing copy and install operations, therefore invalidating part of the cache whenever the source changed).
Providing the `NCORES` build arg lets the editor/user choose how many jobs should be used at the same time, which defaults to 1, but should be set as high as the number of cores in the build machine. From my (very …
> Split the dockerfile into two

- .travis.yml
- Dockerfile
This makes what is built on CI a bit closer to what gets deployed and means we only have to keep track of deps in a single place.
~Blocking on xsf/xep-docker-base#1~
> Build xeps container on CI

- xep-0045.xml
To faciliate better interop with Carbons, MUC-PMs need to contain an &lt;x/&gt; tag ([rationale on standards](https://mail.jabber.org/pipermail/standards/2017-January/032048.html)).
This one is a complement to #434.
> XEP-0045: Add <x/> tag to MUC-PMs

- xep-0369.xml
Example 46 and 47 incorrectly uses `<jid/>`.
> XEP-0369: Correct XML syntax.

- xep-0234.xml
There were some xml errors in XEP-0234 (Jingle FIle Transfer).
The content element of Examples 17 and 18 is empty and opened, but not closed.
> XEP-0234: Fix xml of error examples

- xep-0369.xml
Remove Legacy MIX Namespace;
Add mix element in message to hold MIX additional information;
Roster Update Clarifications;
Clarify when messages are delivered to clients;
Extend Roster Get to select format;
Ensure that text defining attributes and elements reference the namespace;
Change mix_nick_register to nick-register;
Separate namespace for roster information;
rename jidmap2 to jidmap-visible;
Namespace bump to mix:1;
> XEP-0369: MIX - Update to 0.9.3

- xep-0390.xml
Changes:
* Server-side disco#info interception based on the capability hash sets published by a resource (*Query Interception*).
* Publishing of caps to the server before sending initial presence (*Gratuitous Capabilities*).
* Clear specification of ``xml:lang`` handling.
> XEP-0390: ecaps2 to version 0.2

- xep-0060.xml
This is after a mailing list discussion about the true meaning of publish options.
[Rendered version](https://gultsch.de/files/xep-0060.html).
> XEP-0060: Clarify behaviour of publish-options. Fields must be registered

- xep-0234.xml
fileTransferRangeType was missing the length attribute in the XML schema.
> XEP-0234: Add missing length attribute to XML Schema

- xep-0388.xml
Updated according to implementation experience:
* Updated namespace
* Continue "mechanisms" are not; changed these to "tasks".
* Added stream features after Success.
* Don't need complexity of "=" encoding; removed.
* Fixed internal links.
* Updated examples.
> XEP-0388: SASL2 Updates

- xep-0357.xml
Let example 12 and 13 in XEP-0357 use the server JID rather than the user JID for publishing notifications, as suggested [on the list][1].
[1]: https://mail.jabber.org/pipermail/standards/2017-July/033050.html
> XEP-0357: Use server JID as 'from' address for notifications

- xep-0234.xml
- xep-0300.xml
As discussed in https://mail.jabber.org/pipermail/standards/2017-August/033116.html
> XEP-0234, XEP-0300: Add hash-used element to hashes and make use of it in Jingle File Transfer

- xep-0388.xml
Fixes:
* That's a lot of XML errors. Sorry.
* Clarified whose additional-data this is.
* &lt:next> uses &lt;initial-response>.
Added a few example flows.
Finally, added a (probably wrong) schema.
> XEP-0388: Fixes, clarifications, and schemas

- xep-0359.xml
This commit changes some of the wording to clarify that the by attribute
for messages tagged by the server should be either the account jid or
the room jid (as opposed to the server jid for example)
To further clarify this the examples (including the disco example) were
all changed to have the same jid/by-attribute. (A room in that example)
The business rules had some wording that an entity would overwrite the
ID in existing 'faked' stanza-ids instead of removing the faked and
re-adding a non-faked one. However that doesn't work for faked messages
that are not archived (don't have a stanza-id).
rendered version [here](https://gultsch.de/files/xep-0359.html)
> XEP-0359: clarifications and removed 'overwrite' wording

- README.md
I'm not sure if it's possible (GitHub's permissions system is neither very clear, or very flexible as far as I can tell) to give other people permission to sort / organize / etc. issues, but I've added a section on that just in case. Maybe it would be helpful (or maybe no one would do it, no idea; take it as a suggestion).
Also included a section on accepting protoxeps and updating existing xeps.
Left out anything about archiving because it's still manual and might change soon.
Thoughts? Better or worse than the existing document?
> README: move editor readme to markdown readme

- xep-0045.xml
TL;DR: whenever a client (re)sends a join, the MUC service should return
everything a newly joining client needs to know.
Discussion in
https://mail.jabber.org/pipermail/standards/2016-June/031180.html
> XEP-0045: Clarify wording for a client re-syncing to a MUC

- xep-0234.xml
as noted in https://mail.jabber.org/pipermail/standards/2017-August/033128.html
> xep-0234: fix broken internal link

- xep-0065.xml
Example 10 was a duplicate (the stanza was a copy of ex. 9, the description a copy of example 11) so I removed it.
> XEP-0065: Remove duplicate example

- xep-0319.xml
This section is non-normative, and is already specified more strongly in XEP-0082, so it shouldn’t change anything.
> XEP-0319: Make the schema more precise about a date being a xs:dateTime

- xmpp.css
XEPs are currently very hard to read even on fairly standard sized 1080p monitors because the text is more-or-less full width. It would also be nice to scale the fontsize based on the viewport size at a later date, but incremental changes.
/cc @guusdk because I think the website serves this file from somewhere else and it might have to be copy/pasted (sigh)
> Limit text width of XEPs on large viewports

- xep-0286.xml
Removes the reference to EXI (which has no usable impementations as far as I can tell), and other minor editorial and citation fixes.
> XEP-0286: various editorial fixes

- xmpp.css
> Hide overflow (with scroll) on long code blocks

- README.md
We can revert this if/when we decide to use GitHub projects.
> Remove references to GitHub Projects in README

- xep-0030.xml
I was using the XML schema files provided by XEP-0030 to validate some XMPP traffic and stumbled upon a stanza that did not pass the validation process because the order of identities and features was wrong.
I carefully read the specification and asked the jdev muc for advice, we came to the conclusion that the schema file is too restrictive and the order of identities and features should not be forced.
This PR removes the order forced by the current schema.
> XEP-0030: Service Discovery - Removed the order restriction of identities/features in the disco-info XML schema

- inbox/jet-omemo.xml
JET-OMEMO thrives to specify usage of JET (XEP-0391) via OMEMO to utilize OMEMO encryption to secure Jingle Transports.
> Initial version of jet-omemo

- xep-0060.xml
XEP-0060 § 6.5.4 requires compliant implementations to also implement
XEP-0059.
> XEP-0060: Add dependency to XEP-0059

- inbox/styling.xml
Add a new protoxep to the inbox.
> This specification defines a plain-text formatting syntax for use in
> exchanging instant messages with simple text styling.
> add styling protoxep to inbox

- xep-0373.xml
Also weaken the requirement regarding PEP persistence.
> XEP-0373: Specify values that send_last_published_item should be set to

- xep-0060.xml
Adding this features will help clients to be sure that the server can support several items per node, required for future changes on PEP and PEP-related XEPs.
> XEP-0060: Add pubsub#multi-items in Publish-Subscribe features

- xep-0095.xml
- xep-0096.xml
- xep-0166.xml
- xep-0234.xml
Also mark XEP-0166 and XEP-0234 as superseding the older specs.
Second commit issues LC for 0234.
> XEP-0095, XEP-0096: Deprecate

- xep-0369.xml
Various Clarifications from Georg Lukas review:
Role Membership reword,
Participant's Node Joining clarification,
Joining Channel Clarification, 
Coming online clarification,
Going offline JID error,
Allow servers to limit retract time frame,
Clarify that private messages must not be groupchat,
Creating Channel Clarification,
Address security concerns on Converting a 1:1 Conversation to a Channel, 
Remove requirement for all user clients to support MIX,
Change Retract to use MAM-ID;
Ensure use of .example throughout (follow RFC conventions);
> MIX - XEP-03698 update to 0.9.4

- xep-0369.xml
Various Clarifications from Dave Cridland review:
Remove Recommendation to do MIX/MUC on separate domains,
Sort Default JID Visibility Preference,
Make Owner optional,
Clarify that Nick is optional;
> Mix - XEP 369 update to 0.9.5

- xep-0393.xml
A few more incremental improvements to styling. Hopefully this makes writing parsers clearer.
> XEP-0393: clarify quote and plain behavior

- xep-0387.xml
Kev pointed out on list that it was already rejected, so retracting it was rather pointless and we should leave it in the state that it was last in. Fixing to be "Rejected" instead of "Retracted".
> XEP-0387: rejected by the council

- xep-0060.xml
as per discussion on the XSF channel today get rid of both OVERRIDE and metadata publish-options and remove ability to specify new publish-options instead introduce 1:1 mapping to node configuration.
> XEP-0060: Introduce 1:1 mapping between publish-options and node configuration

- xep-0174.xml
As per RFC 6120, <starttls/> only as a <required/> element.
> XEP-0174: Fix samples, <starttls/> does not have an 'optional' element

- Dockerfile
xmpp.org/extensions/refs wasn't built.  As these files are referenced
from xml2rfc.tools.ietf.org, we probably should.
> Build refs for Docker image

- xep-0393.xml
Fixes a broken definition for spans, simplifies some block handling, and reorder sections to be in the order you would probably write a parser.
> XEP-0393: simplify block handling, reorder sections, fix span definition

- xep-0045.xml
Proposal to resolve [standards@ discussion about handling of service-caused removals](https://mail.jabber.org/pipermail/standards/2017-December/034058.html).
TL;DR: Clients should be able to know that a user was removed due to an error and not due to misbehaviour to be able to show a proper UI for this.
Compatibility:
* Server implements it, client does not: existing behaviour continues.
* Client implements it, server does not: existing behaviour continues.
* Client and Server implement it: improved UX by being able to display kicks due to errors differently.
> XEP-0045: Specify 333 status code

- xep-0401.xml
* Use Data Form for In-Band Registration as required by XEP-0077
* Fix error stanzas as required by RFC 6120 § 8.3.2
* Change error of "invalid-token" error to "modify"
> XEP-0401: Use Data Form for IBR and fix error stanzas

- xep-0379.xml
This series fixes a chapter anchor, unifies the action on all xmpp: URIs to `roster` and adds a reference to XEP-0401.
> XEP-0379: minor editing

- xep-0122.xml
where people do not really expect it.
> XEP-0122: Do not put normative language into footnotes

- xep-0153.xml
As per list discussion https://mail.jabber.org/pipermail/standards/2018-February/034362.html .
> XEP-0153: Clarify encoding of update hash

- xep-0163.xml
It sounded like annoucing the jabber.org/protocol/foo+notify feature
causes one to receive notifications from *all* nodes related to the
jabber.org/protocol/foo protocol, but as per XEP-0060 § 9.2, one will
only receive notifications of the node whose NodeID equals
'jabber.org/protocol/foo'.
> XEP-0163: Clarify how +notify works

- xep-0107.xml
It was previously using Ralph’s domain, which didn’t make it clear that it was a dummy example.
> XEP-0107: Change the namespace of a private example

- xep-0223.xml
In light of [CVE-2018-6591](https://gultsch.de/converse_bookmarks.html), it seems reasonable to make this clearer.
Variants (Council, feel free to mix and match):
* Raise the discovery to a MUST.
* Move "Determining Support" before the examples of the publish flow.
> XEP-0223: Add a warning about publish-options support

- xep-0122.xml
regarding the emptiness of elements. There is no point having that,
it just prevents potential (but unlikely) future extensions and adds
additional noise to the text.
> XEP-0122: Remove unnecessary normative wording

- xep-0369.xml
The owner field is defines as `jid-multi`, so multiple values should be presented in one field parent, not two.
> XEP-0369: Fix data form jid-multi example

- xep-0393.xml
Someone was asking why bold wasn't a form of emphasis; "strong" is just the HTML element name which I borrowed. Clarify the language to read "strong emphasis" to make things more clear.
> XEP-0393: clarify language around strong emphasis

- xep-0260.xml
It was marked as optional, despite the text saying otherwise.
> XEP-0260: Fix the schema to mark @sid as required

- xep-0373.xml
XEP-0373 is falsely linking to RFC-4880 §11.1. Transferable Public Keys, while the context is about secret keys. So instead it should link to the next chapter about Transferable Secret Keys. This is just a nit, but imo it should be corrected.
> XEP-0373: Fix link to RFC-4880 §11.2. Transferable Secret Keys

- xep-0373.xml
This PR adds an example about how the metadata node is being fetched.
It also fixes a small typo in one of the anchors.
> XEP-0373: Add pubsub example

- xep-0373.xml
The client adds a keys fingerprint to the metadata node, not the key id.
> XEP-0373: Replace "ID" with "fingerprint"

- xep-0198.xml
The note was only 50% correct (the counter the note talks get
initialized and started when the entity receives <enable(d)/>, and not
when it is sent) and partly misleading (there are typically four
counters per stream). Most XEP-0198 Stream Management implementations
I am aware of didn't get the counters right at the first time. The
tricky part is to get the time right where the counters should be set
to zero and get started. The new note's text tries to help
implementers with this. As bonus, it is also shorter than the original
note.
> XEP-0198: Clarify the note about counters

- inbox/fsn.xml
Remark:
Seperated parts about the usage of chat states and moved the definitions of
types to their examples.
> inbox/fsn.xml: Restructure & add new revision (0.0.2)

- xep-0157.xml
It was present in the text, but not in the metadata.
> XEP-0157: Add a forgotten dependency on XEP-0128

- xep-0373.xml
Fix the name of the secret key node to follow the same pattern as the other node names.
This was originally part of #644 but I moved the change over here to allow #644 to get merged faster.
> XEP-0373: Fix node name of secret key node

- inbox/muc-selfping.xml
This specification defines an XMPP protocol extension for sending application-level pings over XML streams. Such pings can be sent from a client to a server, from one server to another, or end-to-end.
[Rendered version](https://op-co.de/tmp/muc-selfping.html)
> muc-selfping: "Schrödinger's Chat" ProtoXEP

- inbox/muc-selfping.xml
Patches after first Council discussion:
- Rename according to Council feedback
- Document nick change / 'item-not-found' response, thx jonasw
> muc-selfping: Council and floor feedback

- xep-0398.xml
> XEP-0398: Fix usage of <strong/> vs. <cite/> and German vs. English double quotes

- inbox/muc-avatars.xml
After much pondering on whether or not to rewrite this XEP against XEP-0084 instead of XEP-0153, I came to the conclusion that I’d rather see the current way documented than wait for a hypothetical better solution a lot further away.
A rendered version can be found at https://linkmauve.fr/extensions/muc-avatars.html
> ProtoXEP: MUC Avatars

- xep-0060.xml
The `<entity/>` element has been replaced with the `<subscription/>` element
since at least version 1.8. Text in several sections is updated to use
the `<subscription/>` element, making it consistent with the XML snippets.
Ref: https://mail.jabber.org/pipermail/standards/2018-July/035282.html
Signed-off-by: Melvin Vermeeren <mail@mel.vin>
> XEP-0060: correct "entity" to "<subscription/>"

- xep-0001.xml
Rationale: Sometimes, XEPs linger in Last Call state. This is probably for the same reason as XEPs which linger in Experimental state (and then become Deferred). However, currently there is no way to put Proposed (= Last Call) XEPs back into Experimental state if one follows the XEP-0001 process by the letter.
This is unfortunate, because it puts council into the position to either:
- Reject a XEP which is actually useful, but needs work before going to Draft (note that "Rejected" is a final state in the transition graph), or
- Advance a XEP to Draft which isn’t ready yet, or
- Burn cycles of the Editors and Council on perpetuating a Last Call which won’t lead to a conclusion at the current time.
(The "burning" of "cycles" is mostly due to the noise created by either officially extending …
> XEP-0001: add state transition Proposed -> Experimental

- xep-0369.xml
remove node='mix' for channel discovery;
ensure conference is type mix, and note registration requirements;
fix retract id example; 
clarify that channels always created with default parameters;
change to reflect that XEP-0004 does not support multiple languages;
editorial;
> MIX CORE (XEP-0369) update

- xep-0367.xml
The current version of the XEP currently only uses the 'id' attribute, which is a namespace shared by all clients in a MUC, leading to collisions and race conditions.
This update switches it to use the stanza-id assigned to the message by the MUC.
> XEP-0367: Update to specify the correct ID to use within MUCs

- xep-0369.xml
It's defined differently here: https://xmpp.org/extensions/xep-0369.html#info-node
> XEP-0369: Remove MIX xmlns from pubsub <item/>

- xep-0412.xml
- removed XEP-0184 from Advanced Server (doesn’t make sense)
- removed XEP-0084 and other avatar things from Core clients
- removed XEP-0368 from Core Server
- un-require RFC 7622 and add a note
> XEP-0412: version 0.2.0

- inbox/hash-recommendations.xml
Mostly copied from XEP-0300, which this ProtoXEP is supposed to
partially replace in the future.
> ProtoXEP: Cryptographic Hash Function Recommendations for XMPP

- xep-0384.xml
This makes it respect XEP-0060 §12.20 on singleton nodes.
> XEP-0384: Make examples use item id='current'

- xep-0156.xml
Adding `Access-Control-Allow-Origin: *` header allows web clients hosted on different domains access connection settings for target servers.
This change adds similar suggestion that is already present in [XEP-0363 HTTP Upload][0].
See: https://mail.jabber.org/pipermail/standards/2019-January/035645.html
[0]: https://xmpp.org/extensions/xep-0363.html#impl
> XEP-0156: Add implementation notes suggesting CORS

- xep-0284.xml
XEP-0030 was from the `http://jabber.org/protocol/*` era,
nothing else uses `http://xmpp.org/protocol`.
This appears to be a mistake, which is corrected in this PR.
I have not added a revision block, but can do if it's needed.
> xep-0284: Fix xmlns in disco#info examples

- xep-0260.xml
when sent by responder accroding to requirements above
> XEP-0260: mode attr must not be included

- xep-0313.xml
Because "Namespace bump" is really not helpful when you are doing XEP archeology.
> XEP-0313 (editorial): add bumped version into changelog

- inbox/dox.xml
- xep.ent
There is [running code](https://github.com/moparisthebest/jDnsProxy/tree/dox) that implements this, as well as a resolver anyone can poke running at [dns@moparisthebest.com/listener](xmpp:dns@moparisthebest.com/listener)
I would humbly suggest this might be accepted as a XEP on the first of next month, if council approves. ;)  Feel free to contact me via XMPP with any questions.
Rendered version: https://www.moparisthebest.com/dox.html
Thanks!
> ProtoXEP: DNS Queries over XMPP (DoX)

- xep-0199.xml
8.2.3. of rfc6120 noted type "result" MUST have one or zero childs. I suppose it is a typo because other examples use type "error".
> Fix typo in XEP-0199

- xep-0050.xml
According to the previous example, the first variable should be called `runlevel` instead of `mode`.
> XEP-0050: Fix variable name in example 14

- xep-0412.xml
As agreed in the last Council meeting, I'm taking over the toxic Compliance Suite XEP and adding my own agenda to it:
* Better wording of Category and Level
* XEP-0313 and XEP-0412 are now part of "Advanced Group Chat", for lack of a better name
> XEP-0412: take over and push agenda

- xep-0060.xml
This attribute had been added in revision 1.13, but only the pubsub#event schema had been updated, this fixes it for the pubsub schema too.
An example of this attribute being used can be seen in [example 105](https://xmpp.org/extensions/xep-0060.html#example-105).
> XEP-0060: Add missing @publisher in pubsub schema

- xep-0084.xml
There are many avatars out there being bigger than 255×255, this lets implementations relying on the schema accept them.
> XEP-0084: Bump the maximum of @width and @height to 65535

- xep-0280.xml
XEP-0296 is Deferred and appears unrelated, while XEP-0297 is Draft and
actually used by XEP-0280.
> xep-0280: Fix off-by-one in dependency

- Dockerfile
This includes the target that copies the source XML files into the build dir, fixing [404 errors](https://xmpp.org/extensions/xep-0203.xml) for these.
> Include source XEP XML files in build

- xep-0184.xml
Because it led to ambiguity in the past, here is a small informational box about reflecting the message type in Receipts.
> XEP-0184: add a box about types and JIDs

- Makefile
- xep.xsl
This should help with "undefined entity" errors when viewing the XEP XML
files online.
E.g. https://xmpp.org/extensions/xep-0030.xml currently shows:
```
XML Parsing Error: undefined entity
Location: https://xmpp.org/extensions/xep-0030.xml
Line Number 11, Column 5:
&LEGALNOTICE;
----^
```
> make xml: Include  XEP XML dependencies in output

- xep-0045.xml
This patch set delivers (with a bit of delay) on my promise of providing a PR for GC1.0 removal, as discussed and agreed upon in https://mail.jabber.org/pipermail/standards/2018-April/034768.html
It does the following:
* change wording that claims compatibility with GC1.0
* move the GC1 section from the top to the bottom of 'Entering a Room' (thx Zash)
* mandate that a service SHOULD kick a non-occupant sending a GC1.0 join / presence update (thx Kev)
> XEP-0045: kill GC1.0 with fire

- xep-0405.xml
> In addition to this the server MAY advertize the __'urn:xmpp:mix:pam:1#archive'__ feature
> XEP-0405: Fix namespace typo in example

- xep-0280.xml
This is a re-work of https://github.com/xsf/xeps/pull/434, which got closed for purely formal reasons.
This time without Hints and without version-bumping the weasel words:
* https://github.com/xsf/xeps/commit/a95dab9099f8ec558215c614f6d2c414c1dca7c7 Improvement of the "Messages Eligible for Carbons Delivery" section that conveys the same set of rules in less words
* https://github.com/xsf/xeps/commit/4b51c8b16696d8bed597ad2766bd6c2c84e07dcb addition of clear MUC / MUC-PM instructions, as [suggested on standards@](https://mail.jabber.org/pipermail/standards/2017-January/032048.html)
* https://github.com/xsf/xeps/commit/820d7f1fb688051904c902165b9cf2000f0e73b3 minor wording correction to accomodiate the above changes
* https://github.com/xsf/xeps/commit/c7ce94918b014be2144666abb709ea8fcb172 …
> XEP-0280: Rewrite of the 'Messages Eligible for Carbons Delivery' section

- xep-0234.xml
Most likely smeone just forgot to update the exampe after introducing hash-used in this xep.
> XEP-0234: Use <hash-used/> to signify the hash function being used, instead of an (invalid) empty <hash/>

- xep-0060.xml
This will allow clients to display proper information regarding the nodes configuration in their UI, especially when combined with the Affiliations and Subscriptions states (hide the publish icon, display an "open/public" node icon…).
> XEP-0060: Expose pubsub#access_model and pubsub#publish_model 

- xep-0315.xml
The shortname was 'media-element', which is already taken by XEP-0221:
Data Forms Media Element. It is likley that the shortname of XEP-0315
was errorneously set to 'media-element' caused by the author using
XEP-0221 as template for XEP-0315.
Shortnames of XEPs should be unique, hence this changes the shortname
of XEP-0315 from 'media-element' to 'xml-element'.
> Fix shortname of XEP-0315: Data Forms XML Element

- inbox/occupant-id.xml
> This specification defines a method that allows clients to identify a MUC participant across reconnects and renames. It thus prevents impersonification of anonymous users.
> ProtoXEP: Anonymous unique occupant identifiers for MUCs

- xep-0184.xml
Even though the text only says “[an entity] SHOULD include an 'id' attribute”, there is really nothing to do without one.
> XEP-0184: Make the schema require @id in <received/>

- xep-0371.xml
Fixes the text to use the correct element name which is used in the sample and the schema
> xep-0371: fix gathering-complete text

- xep-0410.xml
Although the example shows the correct string, the normative text
potentially leaves the impression that the feature string is only
'self-ping-optimization', i.e. without the
'http://jabber.org/protocol/muc#' prefix.
> MUC Self-Ping (XEP-0410): Clarify the feature string

- xep-0128.xml
With various XEPs (XEP-0157, XEP-0232, XEP-0363) depending on Service Discovery Extensions,
it is no longer 'unlikely' that more than one extension is added.
> XEP-0128: Remove 'unlikely' statement.

- xep-0387.xml
- xep-0412.xml
Now that [Compliance Suites 2019](https://xmpp.org/extensions/xep-0412.xml) has been published, we shouldn’t keep the [2018 version](https://xmpp.org/extensions/xep-0387.xml) lingering in Draft status for any longer.
> XEP-0387: Obsolete Compliance Suites 2018

- xep-0060.xml
This will already be useful as is. Some more PRs should follow regarding RSM/Order-by, and more specific disco#info features in other XEPs.
> XEP-0060: Add a pubsub#rsm disco#info feature to clear confusion

- xep-0280.xml
This commit adds a negative (attack) example to the XEP, to improve developer awareness.
> XEP-0280: negative Carbons example

- inbox/message-retraction.xml
- xep-0402.xml
- xep.ent
* The MUC moderation use-case will be split out into a different XEP
* Update this XEP to handle the case where a user retracts their own message
* Use XEP-0422 for the retraction message
* Mention in security considerations that the XEP-0421 occupant id must be checked
In the [standards email list](https://mail.jabber.org/pipermail/standards/2019-September/036412.html) @legastero has agreed to let me edit this XEP, so AFAIK his explicit approval for this PR isn't necessary.
That said, feedback is welcome (on list if not directly related to the PR).
> Message Retractions protoXEP

- inbox/message-moderation.xml
* Send an IQ to a groupchat service to retract a message
* The groupchat service is responsible for sending out a retraction message
* Use XEP-0422 for the retraction message sent out by the service
~Note: I'm making this PR against the `message-retractions` branch, because it relies on that branch being merged first.~
> New protoXEP: Message Moderation

- xep-0335.xml
The LC never ended and it was agreed by council and the author to put it
back.
> [T]here's only the last call vote for XEP-0335, which got passed. We did
> a Last Call, but I don't see any subsequent vote on advancing it to
> Draft - equally, I do see feedback and no new version, so...
> After a quick chat with Matt, I'll leave '335 for now.
https://logs.xmpp.org/council/2019-05-21?p=h#2019-05-21-49640fd1dbb137b1
Technically editor realm with that quote from Dave, but maybe @horazont has more insight?
> XEP-0335: Back to Experimental

- xep-0402.xml
This PR might be more easily read commit per commit.
Rendered version: https://linkmauve.fr/extensions/xep-0402.html
I was extremely surprised at the difference of treatment for notifications between publishing an item (XEP-0060 §7.1.2.1) and purging all items (§8.5.2), both sending a notification if the node is configured for that, and retracting an item (§7.2.2.1) where the **publisher** additionally has to include a `notify='1'` attribute on the `<retract/>` element.
Another issue we’ve identified during the Sprint is password migration, as much as I dislike this feature there are existing MUCs being protected by passwords, and we most likely keep those until we decide on either removing this feature from MUC altogether, or find a more secure way to store passwords on the server. …
> XEP-0402: Fix issues found during Stockholm XMPP Sprint

- xep-0410.xml
Rationale is inline. Summary: those errors indicate unreachability
of the server and most certainly not (with confidence) that the
client has been removed from the room.
> XEP-0410: treat remote-server-{not-found,timeout} like timeout

- xep-0328.xml
Rendered version: http://geekplace.eu/xeps/xep-jidprep/xep-jidprep.html
Diff: http://geekplace.eu/xeps/xep-jidprep/diff.html
Diff (side-by-side): http://geekplace.eu/xeps/xep-jidprep/diff-side-by-side.html
To quote @legastero: 
> 20190908T17:54:10Z 000 <Lance>  flow: consider 328 yours to update. browsers have exposed string normalization functions since that was written in 2012/2013, so it is possible to do prepping in the browser now without needing half a mb of data tables
The XSF Editor may want to add rfc8264 to `xep.ent`.
> XEP-0328 (jid-prep): Update to 0.2

- xep-0084.xml
The previous revision was using `xs:unsignedInteger` which isn’t defined.
> XEP-0084: Use an existing XML Schema data type for bytes

- xep-0393.xml
Tweak whitespace trimming in block quotes to indicate that only the first space should be trimmed. Also clarify how block quotes are terminated.
> XEP-0393: clarify quote termination and trimming

- xep-0372.xml
All these URIs were missing a ";".
> XEP-0372: Fix incorrect pubsub URIs

- xep-0076.xml
Extensions elements in IQ go as sub-child element into the direct IQ
child element (of which IQs usually can only have at most one).
> XEP "Malicous Stanzas" (XEP-0076): Fix IQ example

- xep-0060.xml
Not being able to set max_items to 'undefined' or 'unlimited' prevents publish_options to work with Bookmarks 2.
> XEP-0060: Clarify unlimited behaviour for node config

- xep-0328.xml
Preparation not Preperation (not "e" but "a")
> Preparation

- xep-0422.xml
I assume that the author meant 'message fastening' here, and that 'reactions' is a remnant from a past version.
> XEP-0422: s/reactions/message fastening

- tools/extract-metadata.py
Sometimes the main working directory may have other XML files such as
the temporary files generated by TeXML (xep-*.tex.xml) which may be
picked up by the metadata script. Use a more specific pattern so that it
only extracts metadata from real XEP files.
> tools: be more specific about XEP filenames

- Dockerfile
By performing the build in one image (with all the needed tools)
and then copying over the result files into an image based on
stock nginx, the image size is reduced from 1.4 GB to 111 MB.
> Reduce final image size by 92%

- xep-0401.xml
This is an update to 0401 that incorporates Council feedback (not to do custom IBR extensions). It is now using a separate pre-IBR IQ to transmit the token to the server.
> XEP-0401: update pre-authenticated IBR

- xep-0393.xml
Previously the styling directive rules indicated that the opening
styling directive must be preceded by whitespace or be the beginning of
the line, however, this meant that a later example was incorrect as it
showed bold and monospace text starting with *` (the second styling
directive is preceded by the first, not whitespace). Allowing styling
directives to immediately follow other styling directives fixes this
oversight.
See siacs/Conversations#3605
> XEP-0393: make span rules match examples

- xep-0363.xml
Addressing some feedback from the current LC.
Rendered version: https://gultsch.de/files/xep-0363.html
> XEP-0363: refined requirements and security considerations after LC

- xep.xsl
This PR introduces two changes to the HTML generation:
1. Use a proper HTML5 doctype (instead of an XHTML 1.0 doctype on HTML5 output served with text/html content type).
2. Fix the ghost whitespaces sometimes found in XEPs, for example in author lists.
Thanks to @Flowdalic for reporting the second issue which made me look into this.
> HTML fixes

- xep-0431.xml
Kev and MattJ argued that Beer constituted an encumbrance.
This changes the language around there to simply use normative language to assert server developers can't be silly.
> XEP-0431: No More Beer

- inbox/trust-messages.xml
An [HTML version](https://olomono.github.io/xeps/preview/xep-xxxx-trust-messages.html) is available.
> ProtoXEP: Trust Messages

- xep-0402.xml
I think I have most comments folded in.
> XEP-0402 Last Call Comments

- xep-template.xml
Having the result and a summary of long or complicated discussions in the document itself instead of list or chat archives serves future readers.
> Add a Design Considerations section to the template

- xep.xsl
Currently the `<section5>` are not processed in the XSL and thus their headlines are not displayed at all. This affects XEP-0060 and XEP-0327. This change only adds the headlines to the rendering (as well as a link and 5 depth number), but not to the ToC.
> Add support for section5 in stylesheet

- xep-0167.xml
This could cause people to think it isn’t useful to validate the namespace here.
> XEP-0167: Add namespace to potentially misleading example

- inbox/muc-presence-versioning.xml
A protoXEP which defines a way to do versioning for MUC presences, thereby reducing the amount of presence-traffic.
The rendered version can be read here: http://xmpp.tech/xeps/build/inbox/muc-presence-versioning.html
> New ProtoXEP: MUC presence versioning

- xep-0369.xml
Better safe than sorry, many implementations blindly follow examples, and these were violating a MUST in XEP-0030.
> XEP-0369: Add missing disco#info feature in examples, and fix xlns→xmlns typo

- xep-0060.xml
Note that to trigger a notify-only publish, the ``<item/>`` must not
be included at all (as said at the beginning of #publisher-publish-request).
> XEP-0060: Specify that empty <item/> are invalid on publish

- Makefile
Fixes a bug that makes `make preview` fail to work unless you create the `build/` tree (or whatever `OUTDIR` is) first.
> Ensure OUTDIR exists before make preview

- xep-0389.xml
A while back @Zash  reached out to me to ask if extensible IBR could be made compatible
with [XEP-0401: Easy User Onboarding]. While working on a solution to this
I decided it would also be nice if it could also allow the user to pick
between several flows (eg. "Verify by Phone" vs  "Verify by SMS").
After working this up I came to realize that the current version of the
spec could not be used to replace [XEP-0077: In-Band Registration] as it is used by [XEP-0045] and
other XEPs because I wasn't using routeable stanzas that could be sent to
components and had no way to discover support other than during stream
feature negotation.
This PR turned into an overhaul of the proposal to fix all these
problems and move the spec back out of experimental.
**Rendered:** …
> XEP-0389: major updates to add more flexibility

- xep-0389.xml
Here are a handful of self-contained commits that make up a new revision of XEP-0389. These include adding a glossary, lots of typo fixes, some clarifications, adding the ability to query for registration/recovery flows after stream negotiation has been complete, the addition of an OOB challenge, and minor changes to the challenge list.
> XEP-0389: new revision

- ref.xsl
XEPs are currently rendered without the URL when referenced from an RFC because target is on a list of formats and not on the root node. This copies the attribute to the root node.
For an example reference see https://xml2rfc.tools.ietf.org/public/rfc/bibxml2/reference.NIST.SP.800-185.xml
> Move ref target attribute to root node

- xep-0390.xml
The remark already talks about the outer elements as potential source
of xml:lang, but it does not explicitly mention the root <stream> open
element as further source. Better to spell this out explicitly to hint
implementors towards it.
> ecaps2: mention xml:lang inheritance from <stream>

- inbox/quick-response.xml
This PR removes @Zash from the list of authors and deletes a few version blocks. These two pieces of information were in the protoXEP for "historical reasons": I started writing this protoXEP by modifying an existing one, but later I rewrote it completely, so the version blocks and the author information is false/outdated. This PR clarifies the state of this protoXEP being a new specification and not a modified one.
I'm not sure whether changes like these are possible in experimental, that's why I'd like to get this in before the council meeting next Wednesday.
> protoXEP Quick Response: Remove some outdated information

- xep-0115.xml
The default form field type is text-single, but the hyptothetical
field ip_version has multiple values and hence can not be of type
text-single.
> caps: fix complex generation example by adding missing form field type

- inbox/cb-pseudomechanisms.xml
This adds a new protoxep that defines a number of SASL "pseudomechanisms" for determining channel binding support in the SCRAM family of SASL mechanisms.
> Add Channel Binding Pseudomechanisms protoxep

- xep-0004.xml
It is not really spelled out that the submitting entity may omit
fields not mark as required by the processing entity. Even though the
existence of the <required/> flag on form fields is a strong hint
towards this, it is worth to explicitly state that.
> XEP-0004: clarify that the submitting entity may omit optional fields

- xep-0436.xml
- Create a separate tag for sending the version number
- Include a reset token
- Remove the "additional measures" section and merge parts into "Requirements"
- Mandate that presences are always sent for affiliated users
> XEP-0436: Updates based on list feedback

- xep-0414.xml
While Blake2b is capable to produce digests of any size from 1 to 64 bytes, It's default mode is 64 bytes (512 bits) though.
Some libraries implement just default digest size.
* OpenSSL supports blake2s-256 and blake2b-512 (no blake2b-256)
* gcrypt supports both blake2b-256 and blake2b-512
* nss supports none of blake2b
* Botan - any digest size
* Java: https://github.com/alphazero/Blake2b - any digest size
* Go-lang: https://godoc.org/golang.org/x/crypto/blake2b - both blake2b-256 and blake2b-512
* Rust: https://docs.rs/blake2/0.8.1/blake2/ - any digest size, 512 by default
* JS: https://github.com/dcposch/blakejs - any digest size, 512 by default
Also various libraries based on openssl will provide just blake2b-512.
So it looks to be a preferable choice over blake2b-256
> XEP-0414: Reverse SHOULD/MUST for Blake2b algorithms

- xep-0068.xml
Follow up on https://github.com/xsf/xeps/pull/913
> XEP-0068: Clarify FORM_TYPE field type on 'submit' type forms

- xep-0393.xml
This was a nice workaround, but a convenient code point that is actually
for this sort of use can't be found. While this still works and can be used in individual implementations, let's not make any specific recommendations at this time.
> XEP-0393: remove disabling individual spans/blocks

- .gitlab-ci.yml
- Makefile
- pack-only.Dockerfile
- tools/archive.py
- tools/ci-announce.sh
- tools/ci-archive.sh
- tools/ci-changed-builds.sh
- tools/ci-prune-build.sh
- tools/ci-restore-timestamps.py
- tools/send-updates.py
This PR configures a GitLab CI pipeline which features the following:
- Building of an nginx image with the XEPs as static files, in all formats.
- Incremental builds on the main branch and incremental builds for MRs based on the last main build.
- Automatic archiving of changed XEPs to the attic
- Automatic announcement to the mailing lists
- Attach rendered versions of changed documents to MRs (Example: https://gitlab.com/xsf/xeps/-/merge_requests/3 click on "exposed artifacts")
This is an experiment. There have been no decisions about a potential move to GitLab.com made yet. We are investigating the use of gitlab.com over github.com for improved CI features.
There will be official communication about this from iteam and editors once gitlab.com actually seems a viable alternative.
> Support experiments on GitLab.com

- xep-0329.xml
The result IQ's <query/> child element does not need to carry the node
information. And in this case the node information was actually wrong,
since "documents/test2.txt" was queried, and not "test2.txt".
> XEP-0329: Fix example 7, remove superfluous 'node' attribute

- xep-0156.xml
The reference to RFC 6120 was incorrect, what this really meant is RFC
6415. But instead of simply s/RFC 6120/RFC 6415/ here, I decided to
reorganize stating the requirements of XRD and JRD a little.
> XEP-0156: reorganize stating XRD/JRD requirements

- xep-0390.xml
> XEP-0390: Explain that ASCII Seperators are invalid only in XML *1.0*

- xep-0156.xml
The XEP-0156 abstract suggests that it defines only one format for use in discovering alternative methods to connect to an XMPP server. However, the XEP clearly describes two ways for the same.
> XEP-0156: Mention Web Host Metadata Link format in abstract

- xep-0045.xml
Per discussion in xsf@ about the UX implications of showing user disconnects as kicks.
*Note: This is a new attempt at #926 - there is only one word changed (as Council requested).*
> XEP-0045 v1.33.0

- xep-0178.xml
A while back it was discussed that XEP-0178 (SASL-EXTERNAL) for s2s was kinda misleading - it says that server should close connection if authentication fails but it seems that "everyone" (at least Prosody[0] and ejabberd) actually fallbacks to dialback in that case.
This PR changes the specification to reflect status quo.
[0] https://issues.prosody.im/1006
> XEP-0178: Clarify SASL-EXTERNAL specification when s2s auth fails

- inbox/xep-pubsub-mam.xml
PR 2 of 3 for XEP-0313 0.7
This is the pubsub querying protocol, split out into a separate document per community consensus.
> xep-pubsub-mam: Split off from XEP-0313

- xep-0060.xml
As discussed [in this mailing list thread](https://mail.jabber.org/pipermail/standards/2020-August/037679.html) the PubSub specification is missing registry entries for the 'retrieve' action and the 'item' key.
This PR adds those to the query type registry submission.
> XEP-0060: Add missing querytype 'retrieve' action and 'item' key to registry submission

- xep-0167.xml
This was apparently missing in the schema, but is described in the normative part and appears in examples.
> XEP-0167: Add missing required attribute in schema for encryption element

- xep-template.xml
When writing a XEP, you sometimes need to use various styling elements and it is hard to decide which one to take.
Therefore, I've added most of the possible XEP XML elements as examples into the template.
[Rendered version](https://op-co.de/tmp/xep-template.html#styling)
> XEP template: add a section with various XEP XML examples

- xep-0277.xml
As the title says, I'd like to encourage the use of the [`atom:generator`](https://tools.ietf.org/html/rfc4287#section-4.2.4) element, at least make developers aware of it. Just adding it there as we all know copying examples is how things work. No need for keywords I think.
I haven't added a version block in case #986 would get in at the same time.
> XEP-0277: Add atom:generator element in examples to encourage its use

- xep-0384.xml
OMEMO implementations ideally want to determine if the PEP service is
suitable for OMEMO. This includes a xep30 feature discovery. This
change makes it easier for implementors to determine the features to
look out for by explicitly mention and linking to the
'persistent-items' feature
> XEP-OMEMO (384): add hint to PubSub 'persistent-items' feature

- xep-0371.xml
Changes:
* RFC 5245 is replaced with RFC 8445
* Introduced `ice2` transport attribute for backward compatibility, same as in RFC 8445
* Clarified ICE restart procedure
* Make `remote-candidate` MUST when `urn:ietf:rfc:3264` is advertised by the responder
* Send `remote-candidate` for all components at once to be better compatible with SIP gateways.
* Wrong reference to RFC 6455 was replaced with correct one: RFC 6544
* Allow gathering-complete element to be combined with remaining candidates
> XEP-0371: migrate from RFC 5245 to 8445

- xep-0389.xml
This defines an error condition if the client attempts to select an invalid flow from the server and cancels the negotiation with a stream or stanza error depending on which side of stream negotiation we're on.
> XEP-0389: error if client selects an invalid flow

- docs/TRIAGING.md
The title should be `ProtoXEP: Title of the new XEP`
rather than `XEP-XXXX: Title of the new XEP`.
> Change title for ProtoXEPs

- inbox/esfs.xml
- inbox/file-metadata.xml
- inbox/sfs.xml
- inbox/stickers.xml
- xep.ent
This pull requests adds four XEP proposals:
- [File metadata element](https://larma.de/xeps/file-metadata.html). This specification defines a generic file metadata element to be used in other specifications.
- [Stateless file sharing](https://larma.de/xeps/sfs.html). This specification describes a protocol for stateless asynchronous file sharing with integrity and transport flexibility. It allows clients to provide a good interoperable user experience in combination with Carbons and MAM.
- [Encryption for stateless file sharing](https://larma.de/xeps/esfs.html). This specification provides a protocol for sharing encrypted files using the stateless file sharing protocol.
- [Stickers](https://larma.de/xeps/stickers.html). This specification provides a protocol to send stickers and to create …
> Add XEP proposals for file sharing and stickers

- xmpp.css
Superscript elements currently aren't styled as superscript. For example, see XEP-0047 which says "65535 (215 - 1)" (which is still wrong either way, but at least the intention would be clearer with the styling).
> Fix styling on superscript elements

- xep-0434.xml
Improve explanations, descriptions and examples, introduce new attribute and complete all sections:
* Remove link to encryption protocol namespaces
* Shorten and improve introduction
* Use emphasizing text formatting instead of quotation marks
* Add new section for explaining the core properties of trust messages
* Add examples comparing trust messages to public key certificates
* Improve description of trust message structure
* Introduce 'usage' attribute for 'trust-message' element
* Focus on XEP-0420 and adjust examples accordingly
* Complete sections 'IANA Considerations', 'XMPP Registrar Considerations' and 'XML Schema'
> XEP-0434: Release version 0.2.0

- xep-0369.xml
- xep-0403.xml
- xep-0404.xml
- xep-0408.xml
Commit titles say most of it, but the most important parts are:
* Fixing the namespace used in MIX-Presence examples
* Fixing the belonging of the form element in MIX-Anon examples (child of user-preference instead of sibling) according to the text
> Fix several mistakes in MIX specs

- xep-template.xml
A few lines of indentation were using tabs and everything else was using spaces. This fixes the indentation to be consistent.
> Fix mixed spaces/tabs in the template

- inbox/mux.xml
Editors: note that before this is accepted there are places in the "Registrar Considerations" section that need updating to include the XEP number once assigned.
> inbox: add new protoxep: Stanza Multiplexing

- xep-0177.xml
It’s a MAY in section 4.2, unlike in XEP-0176 where it is mandatory in each candidate.
> XEP-0177: Made type optional in the schema

- xep-0047.xml
Previously the text said that the max sequence number was 65535 (max
unsigned 16 bit integer), but also said this was (1<<15)-1, which is
actually max signed 16 bit integer or 32767.
This spec is final and therefore will need council review but per [XEP-0001](https://xmpp.org/extensions/xep-0001.html#states-Final) can still be modified in small ways. I think this fits within the scope of "backwards compatible" modifications since it's effectively just a typo fix.
> XEP-0047: fix incorrect max sequence number

- xep-0176.xml
Ping @iNPUTmice on this one.
An alternative would be to describe a way to make up 'id' and 'network' when working with WebRTC.
Foundation is actually described as “[a] sequence of up to 32 characters” [in RFC 8445](https://tools.ietf.org/html/rfc8445#section-5.3), but it is still described as a number elsewhere so not sure which one would be correct, maybe we’d like to take it up to the IETF?
> XEP-0176: Improve compatibility with WebRTC clients

- xep-0447.xml
The example had an element named `<dimension/>`, while the file metadata XEP defines this as `<dimensions/>`.
> XEP-0447: Fix typo in example

- inbox/omemo-media-sharing.xml
This extension is in wide use atm, even though it respects neither the XSF nor the IANA rules it makes sense to have a trace of its existence.
> Resubmit OMEMO Media Sharing on Historical track

- xep-0393.xml
Previously I believe the styling of `***` in the examples was incorrect. After discussing the matter on the mailing list we came to the conclusion that the actual rules were ambiguous and therefore `***` could be styled either way.
To fix this I have clarified the rules to match the existing example on the theory that this is the minimal change that is least likely to break someone who was following the spec as closely as possible and is the most likely to be allowed in a draft PR.
I also added some similar examples.
> XEP-0393: clarify rules for span directives

- xep-0434.xml
Clarify usage, use real namespace for examples and add missing section:
* Clarify usage of trust messages by protocols such as Automatic Trust Management (ATM)
* Use namespace `urn:xmpp:atm:0` of Automatic Trust Management (ATM) as example for `usage` attribute.
* Add section 'Security Considerations'
This should be merged after `inbox/automatic-trust-management.xml` moved to `xep-0450.xml`.
> XEP-0434: Release version 0.3.0

- xep-0452.xml
in order for the MUC to be able to notify them when they're not present.
> XEP-0452: Clarify that users need to have their nicks registered

- xep-0452.xml
The XEP was erroneously referencing to XEP-0279 (Server IP Check) instead of XEP-0297: Stanza Forwarding.
> XEP-0452: Fix reference to Stanza Forwarding

- xep-0009.xml
- xep-0011.xml
- xep-0045.xml
- xep-0060.xml
- xep-0062.xml
- xep-0065.xml
- xep-0073.xml
- xep-0130.xml
- xep-0136.xml
- xep-0154.xml
- xep-0157.xml
- xep-0169.xml
- xep-0176.xml
- xep-0205.xml
- xep-0275.xml
- xep-0278.xml
- xep-0282.xml
- xep-0284.xml
- xep-0289.xml
- xep-0324.xml
- xep-0325.xml
- xep-0353.xml
- xep-0355.xml
- xep-0371.xml
- xep-0379.xml
- xep-0420.xml
Further reading and some rationale for these changes can be found at:
https://tools.ietf.org/html/draft-knodel-terminology-04
All changes are intended to be editorial in nature, not break existing
wire protocols, and not alter the meanings of any text.
> Cross-document editorial adjustments for inclusive language

- tools/xep2md.lua
I have a vague recollection of some problem that was solved by trimming leading and trailing whitespace in spans, but this unintentionally stripped whitespace next to nested spans, such as links, so you'd have text[like this](https://www.example.com/)throughout the markdownified XEPs.
> xep2md: fix spaces around links or spans

- xep-0393.xml
More editorial changes to XEP-0393. Someone pointed out that part of the definition of spans was in the glossary where it's hard to find it. Moving it into the business language makes it easier to find. I also merged a couple of lists of examples and tried to clarify that "new line" == "new block" (mostly).
> XEP-0393: further changes for clarity when reading

- xep-0420.xml
* Use 'envelope' and 'content' consistently by renaming elements
* Update namespace to 'urn:xmpp:sce:1'
@vanitasvitae Here is the outcome of our discussion.
> XEP-0420: Release version 0.4.0

- xep.xsl
I am tired of seeing all those badly or misreferenced XEPs out
there. This produces a high-quality BibLaTeX entry that follows the
recommendations of the biblatex Package and
draft-carpenter-rfc-citation-recs-01 § 5.2 [1].
It also uses proper 'date' attribution, from the first date in the XEP
history to the date of the latest revision entry.
1: https://tools.ietf.org/html/draft-carpenter-rfc-citation-recs-01#section-5.2
> xep.xsl: produce BibLaTeX entry

- xep-0450.xml
Add usage of Trust Message URIs, use more precise sentences, apply consistent formatting:
* Add usage of Trust Message URIs for initial authentications
* Use 'that' instead of 'which' for restrictive clauses
* Apply consistent formatting for paragraphs and revision history
> XEP-0450: Release version 0.2.0

- xep.xsl
Dunno why there's a paragraph with the word END in it, but it was always
at the end and it seems weird to have another appendix after it (ie the biblatex one).
> xsl: Move 'END' to end

- xep-0434.xml
Update to XEP-0420 version 0.4.0 and adapt namespace to shortname:
* Replace SCE's old 'content' element by its new 'envelope' element
* Replace SCE's old 'payload' element by its new 'content' element
* Update SCE's namespace to `urn:xmpp:sce:1`
* Change namespace to `urn:xmpp:tm:0`
> XEP-0434: Release version 0.5.0

- xep-0450.xml
Update to XEP-0420 version 0.4.0 and XEP-0434 version 0.5.0:
* Replace SCE's old 'content' element by its new 'envelope' element
* Replace SCE's old 'payload' element by its new 'content' element
* Update SCE's namespace to `urn:xmpp:sce:1`
* Update TM's namespace to `urn:xmpp:tm:0`
* Update namespace to `urn:xmpp:atm:1`
This should be merged after #1056.
> XEP-0450: Release version 0.3.0

- xep-0450.xml
Improve examples and apply consistent formatting:
* Replace wrong recipient in example by 'alice@example.org'
* Use recipient 'bob@example.com' in examples consistently
* Apply consistent formatting for revision history
> XEP-0450: Release version 0.3.1

- xep-0280.xml
- xep-template.xml
- xep.dtd
- xep.xsd
- xep.xsl
- xmpp.css
This adds a new `<cve>` element to highlight what implementations have done wrong in the past.
> XEP template: add `<cve>` element for security vulnerabilities

- xep-0292.xml
Similar to XEP-0402. Allows easy association between items and roster
entries.
Relevant Standards threads:
https://mail.jabber.org/pipermail/standards/2011-October/025307.html
https://mail.jabber.org/pipermail/standards/2019-January/035710.html
> XEP-0292: Recommend using contact bare JIDs as item IDs

- inbox/preauth-ibr.xml
This is to help start discussion about the possibility of standardizing pre-auth keys in such a way that the XMPP server is not required to generate a key. If this is desired the final output may be changes to XEP-0445 or XEP-0401 instead.
> ProtoXEP: new protoXEP for pre-auth key generation

- xep.xsl
This avoids a potential redirect if the user agent doesn’t support HSTS.
> XSLT: Use HTTPS for every common link

- xep.xsl
This tells the user agent that the page is in English, which it can then use for various natural language operations.
This was reported by this tool: https://wave.webaim.org/
> XSLT: Use lang='en' on the html root

- xep-0369.xml
Every other date (including the month in this revision) uses a two digit day. Fix this so that parsers can be more strict.
> XEP-0369 fix date format

- xep-0413.xml
- Add a way to discover on which protocols Order-By applies
- Remove references to SQL (except in implementation notes)
- Specify that order-by operate on the whole item set and inside a RSM result set
- Explicitly says that creation and modification dates are set by Pubsub service itself
- Specify that Clark notation should be used for extensions
- Add a full example with Pubsub and RSM
- Add hint for SQL based implementations
- removed XEP-0060 and XEP-0313 as dependencies, they are mentioned as use cases, but are not mandatory
- better wording following feedback
- Namespace bump
> XEP-0413: version 0.2

- xep-0060.xml
- xep-0214.xml
- xep-0248.xml
This partially reverts mass replacements of `meta-data` with `metadata`,
as per #710, to ensure that protocol literals don't change.
> Revert `pubsub#metadata` to `pubsub#meta-data`.

- xep-0313.xml
Currently this only explains the difference between the before/after
parameters of RSM and the before-id/after-id parameters of mam#extended.
> XEP-0313: add implementation considerations

- xmpp.css
Due to the change of site generators for xmpp.org, the logo path changed.
> Update path for xmpp-logo.svg

- xep-0384.xml
Update to XEP-0420 version 0.4.0 and adjust namespace:
* Replace SCE's old 'content' element by its new 'envelope' element
* Replace SCE's old 'payload' element by its new 'content' element
* Update SCE's namespace to 'urn:xmpp:sce:1'
* Update namespace to 'urn:xmpp:omemo:2'
This should be merged after #998.
> XEP-0384: Release version 0.8.0

- xep-0270.xml
- xep-0302.xml
- xep-0375.xml
Each CS supersedes its predecessor, and is supersededby its successor, thanks Ge0rG for finding this issue.
> XEP-0270, XEP-0302, XEP-0375: Fix the superseded chain

- xep-0313.xml
A sentence ends with `U+002E FULL STOP`. Found by searching for `[^.]<\/p`.
> XEP-0313: Editorial: Missing paragraph FULL STOP

- xep-0434.xml
Specify key identifier encoding, improve glossary and update to XEP-0384 version 0.8.0:
* Specify usage of Base64 encoding for key identifiers within trust messages
* Specify usage of Base16 encoding for key identifiers within Trust Message URIs
* Use Base64-encoded key identifiers in examples
* Add 'hash value' as example of key identifier
* Update OMEMO's namespace to `urn:xmpp:omemo:2`
* Update namespace to `urn:xmpp:tm:1`
> XEP-0434: Release version 0.6.0

- xep-0450.xml
Update to XEP-0434 version 0.6.0 and XEP-0384 version 0.8.0:
* Use Base64-encoded key identifiers in examples
* Update TM's namespace to `urn:xmpp:tm:1`
* Update OMEMO's namespace to `urn:xmpp:omemo:2`
> XEP-0450: Release version 0.4.0

- xep-0459.xml
This is the way forward, as we deprecated the previous conversion method.
This keeps XEP-0048 stored in XEP-0049 as the preferred bookmarks storage in the absence of the `bookmarks2#compat` feature.
> XEP-0459: Replace deprecated XEP-0411 with XEP-0402

- xep-0384.xml
This PR fixes the given length of the HMAC for encryption.
In the section about `#protocol-message_encryption` it states:
> Truncate the output of the HMAC to 16 bytes/128 bits by cutting off excess bytes from the end.
And then later it says: 
> Encrypt the plaintext (which consists of a 32 bytes key and a 32 bytes HMAC [...]
So the second (32 bytes HMAC) is wrong and fixed in this PR.
> XEP-0384: Fixed HMAC size for encryption

- xep-0402.xml
The other direction is already ok.
Maybe we should have a lint to check that both directions are always set?
> XEP-0402: Add missing supersedes for XEP-0411

- inbox/call-invites.xml
- inbox/compatibility-fallback.xml
- inbox/replies.xml
- **Compatibility fallback**: This document defines a way to indicate that a specific part of the body only serves as fallback and which specification the fallback is for.
- **Message Replies**: This document defines a way to indicate that a message is a reply to a previous message.
- **Call Invites**: This document defines how to invite someone to a call and how to respond to the invite.
> New ProtoXEPs

- xep-0256.xml
XEP-0319 already had the `<supersedes/>` element so no change required here.
> XEP-0256: Deprecate in favour of XEP-0319

- xep-0060.xml
For more information:
- https://github.com/xsf/xeps/pull/986
- https://mail.jabber.org/pipermail/standards/2022-January/038695.html
I also changed the example NS to be slightly more obvious than `http://www.w3.org/2005/Atom` when it comes to semantics.
> XEP-0060: Specify pubsub#type to reflect semantic info

- inbox/pubsub-filter.xml
This is a split of the pubsub-ns protoxep now that pubsub#type is validated. Another one coming with service type restrictions.
Rendered version: https://bouah.net/specs/pubsub-filter.html
> ProtoXEP: PubSub Node Filtering

- xep.xsl
When a XEP has been superseded (or supersedes something else) it's not
always immediately obvious in the HTML output. It exists at the bottom
of the page in the appendices, but this requires a lot of digging, and
in the status message, but this is a big red blob of text that we don't
expect to differ from XEP to XEP and is harder to parse through than the
information we want being in a table.
This adds the information to a third place, the table in the header to
make it accessible at a glance:
> Make XEP superseded more visible in HTML output

- xep-0008.xml
- xep-0038.xml
- xep-0051.xml
As an attempt to clean up our deferred XEPs into the ones we may want to resurrect in the future, and the ones we know we will never want again, I’m obsoleting these three XEPs which all have a more modern equivalent.
> Obsolete some deferred XEPs

- xep-0156.xml
https://mail.jabber.org/pipermail/standards/2022-February/038759.html
> Remove _xmppconnect DNS method from XEP-0156 and add warnings

- xep-0045.xml
The non-MUC way of joining a room has been removed in 1.32.0, but it still was mentioned in a few places.  This removes cases which can’t happen any longer.
> XEP-0045: Remove some more mentions of GC 1.0

- xep-0115.xml
This XEP currently does not mention several [known vulnerabilities](https://mail.jabber.org/pipermail/security/2009-July/000812.html). The security considerations section even suggests that the algorithm protects against this kind of attack.
I am not sure what the best path forward here is, but if it had mentioned it I would have at least considered this when writing my initial implementation, even if it's still not visible enough. Other suggestions welcome, and I'd love to see the council discuss this again.
> XEP-0115: mention the pre-image attacks in the XEP

- inbox/pubsub-public-subscriptions.xml
This specification provides a way to make subscriptions to a node
public.
> Add ProtoXEP: Public Pubsub Subscriptions

- xep-0356.xml
- Add "iq" privilege (necessary to implement XEPs such as XEP-0376).
- Roster pushes are now transmitted to privileged entity with "roster" permission of "get" or "both". This can be disabled.
- Reformulate to specify than only initial stanza and "unavailable" <presence> stanzas are transmitted with "presence" pemission.
- Namespace bump.
> XEP-0356: Release version 0.4

- xep-0308.xml
This commit corrects the JIDs provided in the query/response examples for XEP-0308,
specifically: the request example did not provide a valid `to` attribute, and the response
example did not have matching JIDs for the `from` and `to` attributes.
> XEP-0308: Correct `disco#info` example JIDs

- inbox/xmpp-over-quic.xml
- xep.ent
Already have an open source working implementation [here](https://github.com/moparisthebest/xmpp-proxy) and it's running at MUC service at `xmpp:xmpp-proxy@code.moparisthe.best?join` if you would like to test your s2s implementation without running yourself.
I'm happy for you to hold off council voting on this until June 22nd so I can be around to answer questions, but if you feel like voting earlier that's fine with me too.
> ProtoXEP: XMPP over QUIC

- inbox/websocket-s2s.xml
Already have an open source working implementation [here](https://github.com/moparisthebest/xmpp-proxy) and it's running at MUC service at `xmpp:xmpp-proxy@code.moparisthe.best?join` if you would like to test your s2s implementation without running yourself.
I'm happy for you to hold off council voting on this until June 22nd so I can be around to answer questions, but if you feel like voting earlier that's fine with me too.
> ProtoXEP: WebSocket S2S

- xep.xsl
Comparing versions is a thing you may want to do when dealing with a
more or less living standard. Locating these versions in the attic is
often tedious since there are so many XEPs and revisions.
Linking them from the XEP revision history makes this easier, at least
where the relevant revision does exist in the attic, not all do, and
some are called jep rather than xep for historical reasons.
> Linkify revision history to attic

- xep-0405.xml
Approved by XEP author: https://mail.jabber.org/pipermail/standards/2022-July/038898.html
> XEP-0405: Clarify behaviour on later roster gets without <annotate/>

- xep-0448.xml
- Replace the ProtoXEP reference with a reference to the published XEP.
- Add urn:xmpp:ciphers:aes-256-cbc-pkcs7:0 (same as used in XEP-0384).
> XEP-0448: Encryption for stateless file sharing v0.2.0

- xep-0231.xml
This is a suggestion for where we can find hash names. Sadly, the existing name "sha1" does not match what other XEPs use ("sha-1"), so we make a special exception for historical reasons. This inconsistency can be fixed up in a future protocol.
Alternatively, we could say that only "sha1" is supported unless support for a new namespace, `urn:xmpp:bob#extended` or similar is advertised, but this seems like a lot of work on client devs when "just treat this like a special case and define new hash algorithms" probably doesn't require any more work at all if they didn't already support something that was previously unspecified like "sha256".
> XEP-0231: clarify where to find hash algo names

- xep-0272.xml
Fix typos / grammar / examples and use 'Muji' instead of 'muji' consistently
> XEP-0272: Release version 0.1.2

- xep-0294.xml
Fix example description and attribute name of 'parameter' element as specified by XML schema
> XEP-0294: Release version 1.1.2

- xep-0029.xml
RFC 7622 obsoletes RFC 6122. It stands to reason that XEPs that are marked as being superseded by the former should be updated to be superseded by the latter.
> XEP-0029: Use RFC 7622 instead of RFC 6122 to supersede

- inbox/xep-downgrade-prevention.xml
- xep.ent
This XEP completes SASL2, but I figured that it was better to publish it as an extra XEP:
[RFC 6120](http://tools.ietf.org/html/rfc6120) [[1](https://dyn.eightysoft.de/xeps/xep-downgrade-prevention.html#nt-idm39)] and [Extensible SASL Profile (XEP-0388)](https://xmpp.org/extensions/xep-0388.html) [[2](https://dyn.eightysoft.de/xeps/xep-downgrade-prevention.html#nt-idm43)] define a way to negotiate SASL mechanisms. When used together with SCRAM mechanisms ([RFC 5802](http://tools.ietf.org/html/rfc5802) [[3](https://dyn.eightysoft.de/xeps/xep-downgrade-prevention.html#nt-idm47)]) and channel-binding ([SASL Channel-Binding Type Capability (XEP-0440)](https://xmpp.org/extensions/xep-0440.html) [[4](https://dyn.eightysoft.de/xeps/xep-downgrade-prevention.html#nt-idm51)]) the mechanism …
> New ProtoXEP: SASL SCRAM Downgrade Protection

- Makefile
- refs-LICENSE
Reverts xsf/xeps#1220
It breaks the docker build and I don't have the time to investigate it right now.
> Revert "Add license for bibliographic data"

- inbox/xep-scram-upgrade.xml
This is the SASL2 split-out of the SCRAM upgrade task as announced on standards@.
Rendered version: https://dyn.eightysoft.de/final/xep-scram-upgrade.html
> New ProtoXEP: SASL2 SCRAM upgrade task

- xep-0004.xml
After a discussion on the mailing list a few days ago no conclusion was reached other than "multi-item forms are confusing". I believe this was likely the original intent of the section, and it's likely the simplest solution for now so I've gone ahead and made changes to disallow elements other than "reported" and "items" in multi-item forms. Users who want to mix and match should write a new XEP defining a new field type such as "table" that can contain other fields.
> XEP-0004: clarify rules for multi-item forms

- tools/validate-xep0001-conformance.sh
This adds a simple bash script that checks if a provided file (filename to be provided as first argument) conforms to XEP-0001.
Expected to be executed from the directory that holds all xep XML files. Requires one argument: the file name of the xep to be validated, eg:
$ tools/validate-xep0001-conformance.sh xep-0010.xml
exit status will be non-zero upon validation failure.
requires: bash, xmllint
> fixes #1235: Script that validates XEP-0001 conformance

- tools/validate-xep0001-conformance.sh
Github workflows tend to be verbose. This can make it difficult to determine why a failure occurs.
To help identify causes for validation failures, the output of the XEP-0001 conformance script should have a bit of color to highlight the important bits ([Github supports this](https://github.blog/2020-09-23-a-better-logs-experience-with-github-actions/#opening-the-door-to-a-more-colorful-experience)).
The output will depend on the terminal used to display the content, but will look somewhat like this:
It has:
- newlines before and after the results of each check
- a red-ish color for failed checks
- a green-ish color for passed checks
- a blue-ish color for informational messages
> Add color to output of XEP validation script

- tools/2xep.lua
- tools/xep2md.lua
E.g. lastcall can exist more than once according to the schema, but only
one item was kept by `xep2md`.
Before:
```yaml
lastcall: 2017-11-15
```
After:
```yaml
lastcall:
- 2021-03-30
- 2017-11-15
```
In `2xep`  an extra wrapper element was added
```xml
<lastcall>
<lastcall>2017-11-15</lastcall>
</lastcall>
```
Correct is one element with text for each item
```xml
<lastcall>2017-11-15</lastcall>
```
> Fix metadata conversion in markdown scripts

- tools/extract-metadata.py
- xep-template.xml
- xep.dtd
- xep.xsd
This is but a first step to display tags wherever we think fits. It adds the possibility to add `<tags>` in XEP headers, and it extract this information into `xeplist.xml` that is used by other tools.
> Add tag support in XEPs

- xep-0353.xml
I think explicit is better than implicit, hence this PR.
Since v0.4 of this XEP isn't implemented by any client yet (to my knowledge) and because the XEP is still experimental, I think we can do this update without bumping the namespace.
What do you thing @fippo @stpeter ?
> XEP-0353: Add recommendation for UUID v4 for id attributes

- xep-0461.xml
I think there is no reason that this XEP shouldn't have its associated disco feature.
I am rather confident that direct messages have no reason to refer to the quoted author with a full JID and that a bare JID makes more sense in this context.
I am less confident about permitting no `to` attribute in general and must confess this is something that would make it is easier to comply to the spec for my gateway implementation, but maybe this is not a valid reason. @edhelas since you implemented it in movim, do you use the 'to' attribute? Any opinion on allowing its absence?
> XEP 0461 improvements.

- tools/triage.sh
Fixes #1237
So for a first go this can be ran manually, or ran by a github action and dumped into a comment, or grep'd for "^tag" and used to automatically apply tags by a github action etc
> Add tools/triage.sh

- inbox/muc-avatars.xml
The original ProtoXEP, submitted in https://github.com/xsf/xeps/pull/700, [got rejected](https://mail.jabber.org/pipermail/standards/2018-September/035351.html) due to there being too many XEPs.
Five years later, the situation hasn’t changed at all, nobody defined a new better protocol (my previous attempt [never went anywhere](https://github.com/xsf/xeps/pull/760) after I forgot to submit it to the list), and people still rely on tribal knowledge and from [Ejabberd](https://docs.ejabberd.im/tutorials/muc-vcard/) to write their implementations.
I therefore propose the exact same ProtoXEP, this time on the historical track. In my opinion, numbers are cheap, we can deprecate this one once we do have a better proposal.
> Historical ProtoXEP: MUC Avatars

- xep-0292.xml
While the existing version says this was rejected by community consensus, since then the consensus of most implementations is to use PEP directly even though it was never specified to work, and that the raw-IQ protocol adds complexity.  This update removes the raw-IQ mode and specifies the reuse of PEP.
> Use PEP (and XEP-0222) for XEP-0292

- xep-0388.xml
This is a collaboration between @mwild1 and me. Most parts have already been discussed with the original author @dwd, too.
In short, this adds:
- Namespace bump
- Make SCRAM hashes (and other SASL mechanism families) upgradable
- Add dependency on XEP-0440 for channel-binding agility
- Add new `<inline/>` element as extension point to inline stream resumption and bind2 (and possibly others)
- Clarify of `<continue/>` and tasks in general
- Update security considerations and business rules
- Add optional `<user-agent/>` element
> XEP-0388: Rework whole spec, namespace bump

- xep-0386.xml
This is an extensive update that goes along with the new [XEP-0388 (SASL2) updates](https://github.com/xsf/xeps/pull/1214).
Quoting from the revision change block:
- Various changes, made in parallel with working client and server implementation experience, and   
SASL2 updates.                                                                                     
- More tightly define the integration with XEP-0388 and several session feature XEPs: XEP-0198,     
XEP-0280, XEP-0352.
- Replace the custom latest-id element with the new metadata element from XEP-0313, which also      
provides richer information.
- Drop unread tracking, as this is a deep topic not directly related to resource binding. Instead   
the details of integration with other extensions have been better defined and …
> XEP-0386: New revision v0.4.0

- xep-0428.xml
This incorporates most of the ideas of the ["Compatibility Fallback" ProtoXEP](https://xmpp.org/extensions/inbox/compatibility-fallback.html) as discussed in the council chat room back then.
- Add 'for' attribute such that entities can discover what the fallback is for.
- Allow to specify that only one of `<subject/>` or `<body/>` is meant as a fallback.
- Allow to specify the part of respective text that is meant as fallback where applicable.
- Don't use encryption example, which should use XEP-0380 instead.
> XEP-0428: Fallback Indication v0.2.0

- xep-0223.xml
In reaction to [CVE-2023-28686](https://dino.im/security/cve-2023-28686/). While technically about XEP-0402, all uses following the XEP-0223 pattern should take heed.
> xep-0223: Add origin checking to security considerations

- xep-0313.xml
These were [initially reported](https://logs.xmpp.org/jdev/2023-01-16?p=h#2023-01-16-3eedf318e3ba95f6) by @truenicoco.
Corresponding [mailing list thread here](https://mail.jabber.org/pipermail/standards/2023-March/039209.html).
The largest issue is that the XEP says a server MUST include `<start>` and `<end>` elements in the archive's `<metadata>`. However, if the archive is empty, this is clearly impossible. We checked Prosody's implementation, and it sends an empty `<metadata>` element in this case. I think this is the sensible solution (the only other one that came up is returning an error).
This adds a MUST to a draft spec, which I don't do lightly - however I think it is reasonable given that implementations didn't really have many other options, and it benefits interoperability to …
> XEP-0313 v1.1.0: Clarify a couple of edge cases

- tools/2xep.lua
This tool is handy to import from e.g. Markdown to XEP XML. Unfortunately I had problems with it emitting XML that wouldn't build. The changes in this branch allowed me to build the resulting XML using pandoc 2.9.2.1.
> 2xep tool fixes

- inbox/xep-reporting-account-affiliations.xml
This specification documents a way for an XMPP server to report to other entities the relationship it has with a user on its domain.
> New ProtoXEP: Reporting Account Affiliations

- xep-0317.xml
Despite being a popular concept that the community keeps coming back to, this XEP has lingered in an unfinished state for some time. This small update fixes some of the fundamental issues.
The current version did not actually specify a syntax for hats, as this was still under discussion at the time. Based on discussions with other community members, and personal implementation experience, this update specifies the syntax to be used.
> XEP-0317: New revision 0.2

- xep-0333.xml
The 'discover support' example should not use a server/domain JID, as there's precious little for servers to support. Instead, a client JID is used.
> XEP-0333: Change 'discover support' example

- xep-0474.xml
This is version 0.3.0 of the SSDP XEP simplifying the protocol and reworking the whole explanation why this xep is needed to be more clear.
> XEP-0474: Rework description and simplifiy protocol

- xep.xsl
One major problem when citing XEPs is that they are often cited using links to the living, that is mutable, version of the XEP. For example: https://xmpp.org/extensions/xep-0123.html
However, we really want people to be able to cite an immutable document. Luckily, we have the [`attic/`](https://xmpp.org/extensions/attic/) where we keep immutable versioned XEPs that can be referenced.
This PR changes the XSL so that the immutable versioned XEP URL is used for the generated biblatex entry.
However, it is unfortunately not read yet. Primarily because we do not seem to keep a immutable versioned variant of the *latest* version of a XEP. If we could change the editor workflow to also create a versioned XEP in `attic/` for the latest version of the XEP, then this could be merged.
That said, …
> Use link to immutable versioned XEP in biblatex's "url" entry

- xep-0483.xml
This PR is in response to [this request](https://www.mail-archive.com/standards@xmpp.org/msg23624.html)
>Hi,
>This XEP has two parts:
>1. An IQ-based protocol to request a meeting link from a server.
>2. An additional element to add to a message to send the meeting link
to another party
>
>The second feature is already available via XEP-0482, which describes
call invites using Jingle and external URIs. The XEP already mentions
weblinks to join the call as an example for such external URIs.
As XEP-0482 has a bunch of other features, like announcing join and
leave on the XMPP side (works especially great if the website is opened
in a frame or similar inside the XMPP client, as the XMPP client then
even knows when the user left the call) or the ability to additionally
announce dial-in …
> XEP-0483: Use XEP-0482 to send meeting URL to invitees

- inbox/pubsub-server-info.xml
This defines a data format and a pub-sub based way of distributing data that describes an XMPP domain and its connections to federated domains.
My direct purpose of drafting this specification is to document the data format used to populate the XMPP network graph that, at the time of writing, is hosted at https://xmppnetwork.goodbytes.im/
> ProtoXEP: PubSub Server Information

- xep.xsl
In https://github.com/xsf/xeps/pull/1300#issuecomment-1850475278 it was said that we do not longer simply bump the copyright year range. But keeping the copyright year at 2021 of all XEPs, including newer ones from 2023, is also far from ideal.
So let's simply extract the copyright year from the revision information we already have.
> Extract the copyrigh years of a XEP from its revision

- Makefile
The Makefile was set globally to silent, which caused the failing commands to be *not* displayed. For example
```bash
flo@neo-pc xeps-xsf $ make html
make: *** [Makefile:112: build/xep-0001.html] Error 1
```
Removing this provides usefull information about which command failed:
```bash
flo@neo-pc xeps-xsf $ make html
xmllint --nonet --noout --noent --loaddtd --valid "xep-0001.xml" ! xmllint --nonet --noout --noent --loaddtd --xpath "//img/@src[not(starts-with(., 'data:'))]" xep-0001.xml 2>/dev/null && true make: *** [Makefile:110: build/xep-0001.html] Error 1
```
> Makefile: remove .SILENT, make the targets loud

- xep-0133.xml
Retrieving a password implies storage of plaintext passwords. That's no longer an acceptable practice.
> XEP-0133: Retract 'Get User Password' command

- xep-template.xml
The Privacy section is a new one, and Accessibility was previously optional.
Rationale for the new section: it makes sense to distinguish between security and privacy, even if there is an overlap.
Rationale for requiring both: not making accessibility and privacy part of the core things required for a XEP is bad in this day and age, even if I expect that most XEPs will not have much applicable on those topics. It will make sure the authors have to consider those aspects before submitting.
> xep-template: Require accessibility and privacy sections

- xep-0060.xml
Fix and add examples for publishing items:
* Remove 'item' element specifying its ID from example response for publishing item with ID
* Add examples for publishing item without ID
> XEP-0060: Release version 1.26.0

- xep-0313.xml
XEP-0136 already defines that it is superseded by XEP-0313.
> XEP-0313: Add XEP-0136 to superseded specifications

- .github/workflows/auto-triage.yml
Github won't allow write access on PRs from a fork for security reasons, unless you use the special pull_request_target trigger which then runs in the context of the target and not of the PR.
So we copy the trusted script from the target (master) to /tmp, then checkout the PR, then run the script from /tmp
> Fix auto triage permissions

- .github/workflows/auto-triage.yml
- .github/workflows/xep-validation.yml
This fixes warnings about Node.js 16 deprecation
> GitHub Actions: Update actions/checkout to v4

- xep-0424.xml
Fixes the schema of the `<retracted>` element:
- The is no 'from' attribute
- There is a mandatory 'id' attribute
- 'by' and 'stamp' are not mandatory
Add a fallback for attribute in Example 4.
> Small fixes for 0424

- xep-0045.xml
§7.2.15 is a section dedicated to the room subject and specifies it as a MUST, which conflicted here with the MAY.
> XEP-0045: Remove conflicting keyword in §7.2.2

- xep-0421.xml
- Make explicit that one can't just hash the real JID.
- Expand security considerations.
- Add schema.
- Fix some examples captions and casing
> XEP-0421: Incorporate feedback from Last Call

- xep-0153.xml
The implementation notes in XEP-0054 say “Email addresses MUST be contained in a `<USERID>` element, not included as CDATA within the `<EMAIL/>` element.”
> XEP-0153: Add missing EMAIL/USERID element in example

- xep-0484.xml
> FAST/XEP-0484: Link to latest draft of HT SASL mechanism

- tools/validate-xep0001-conformance.sh
Since it is often encoded as an entity.
For example this is why https://github.com/xsf/xeps/pull/1353 is failing
> Resolve entities when resolving xep number

- xep-0054.xml
In section 3.3 of XEP-0054 it is defined that the same error condition MUST be used in both a case:
- where a VCard request is addressed to an entity that does not exist, and;
- where a VCard request is addressed at an entity for which no VCard is available.
RFC 6121 section 8.5.1 defines:
> If the user account identified by the 'to' attribute does not exist, how the stanza is processed depends on the stanza type. For an IQ stanza, the server MUST return a `<service-unavailable/>` stanza error to the sender.
Prior to this change, both `<service-unavailable/>` and `<item-not-found/>` were offered as suitable conditions to be used in the error scenario defined in section 3.3. For this XEP to be more compatible with RFC 6121, only `<service-unavailable>` can be used.
This commit drops the …
> XEP-0054: Updated error cases to be compatible with RFC 6121

- xep-0386.xml
This has been tested against a mock XEP-0313 schema, because I couldn’t find it listed at [its URL](http://www.xmpp.org/schemas/archive-management.xsd).
> XEP-0386: Add an XML Schema

- xep-0045.xml
Explicitly disallow Ban List modifications that clash with 'Banning a User' conditions.
This follows [a short discussion on the standards@xmpp.org mailinglist](https://mail.jabber.org/hyperkitty/list/standards@xmpp.org/message/CQXCV2DLCVP6RQRLJWR6HXV7E7SDIN5N/).
> XEP-0045: Additional Ban List specifications

- xep-0045.xml
Elsewhere, the specifications dictate that the banlist is based on bare JIDs. Matching resourceparts contradicts this (and is removed by this commit).
This PR follows [this short discussion on the standards@xmpp.org maillinglist](https://mail.jabber.org/hyperkitty/list/standards@xmpp.org/message/CQXCV2DLCVP6RQRLJWR6HXV7E7SDIN5N/).
> XEP-0045 Remove references to using resourceparts when banning users.

- xep-0045.xml
Previously, the wording of the status code purpose incorrectly hinted that the user receiving the presence stanza with the status code is the user that is affected by the corresponding change. This is incorrect, as these status code are not only used in stanzas sent to the affected user. They are also used to inform remaining occupants of the room of the status change.
> XEP-0045: Improved wording of status code purpose

- xep-0045.xml
The pre-existing example appears to show two mutually exclusive acceptable stanzas. This can be confused for a requirement to send two stanzas. In this commit, the example is improved by removing one of the variants. A small textual change has been applied to define the optionality of the 'actor' element.
This change has been discussed:
- on the [standards mailing list](https://mail.jabber.org/hyperkitty/list/standards@xmpp.org/thread/F3W7CHDTLHAYQORUVMU2BS64PVCYGJIK/).
- in the [XSF Discussion chat room](https://logs.xmpp.org/xsf/2024-07-10#2024-07-10-dd0e5a0694e9760b).
> XEP-0045: Improve 'Service Removes Non-Member' example

- xep-0045.xml
This was discussed in the [XSF Discussions chatroom](https://logs.xmpp.org/xsf/2024-07-10#2024-07-10-dd0e5a0694e9760b).
> XEP-0045 Clarify usage of presence stanzas when removing a non-member from a members-only room

- xep-0045.xml
The 'MAY' key word, per RFC 2119, is to be used to flag a 'truly optional' item. In this text, it seems to be used to restrict the item to certain characteristics intead. This is an improper use of the key word.
Further down the section, the scenario is further specified, using more appropriate key word usage.
For context: this was briefly discussed in [the XSF Discussion chat room](https://logs.xmpp.org/xsf/2024-07-12#2024-07-12-db3a9ab26a4fa17c).
> XEP-0045: Replace inappropriate RFC 2119 key word usage in §9.7.

- xep-0045.xml
Section 5.2 defines that affiliations are granted, revoked, and maintained based on the user's bare JID. This commit adds a reference to this definition where affiliations are used (in section 10), and adds a SHOULD to downcast to a bare JID when a request provides a full JID.
This was briefly discussed in the discussion room of the XMPP Standards Foundation ([logs](https://logs.xmpp.org/xsf/2024-08-14#2024-08-14-eb42d4651b7b01d3)).
> XEP-0045: Explicitly use bare JIDs when operating on affiliations.

- xep-0045.xml
In non-anonymous rooms, there's little point in withholding the functionality, as JIDs are visible anyway.
This was briefly discussed in the XSF Standards chat room: https://logs.xmpp.org/xsf/2024-08-14#2024-08-14-f8bc35378ee61874
> XEP-0045: Allow non-owners to retrieve owner and admin lists in non-anonymous rooms

- xep-0402.xml
Currently, the XEP specifies what the client should do if autojoin='1' or if the bookmark is deleted, but it doesn't specify what to do if autojoin='0'
With this PR, we specify that case as well.
Note: multiple "modern" clients already implement the spec change in this PR.
> XEP-0402: Specify what clients should do if autojoin='0' in bookmark notifications

- xep-0045.xml
XEP-0045 explicitly states that modifying the Owner List (section 10.5) is 'forbidden' to any non-owner, but does not explicitly state that error in 10.3 (Granting Owner Status) and 10.4 (Revoking Owner Status). The same issue is there in the sections 10.6, 10.7 and 10.8 (granting/revoking Admin Status).
This commit copies the text that's used throughout the specification ("If the \<user@host> of the 'from' address does not match the bare JID of a room owner, the service MUST return a <forbidden/> error to the sender.") to the sections where it's missing.
> XEP-0045: Add explicit error definition when non-owners attempt to use owner-specific functionality

- xep-0272.xml
- Send Jingle IQs to real JID
- Define how to use with XEP-0482
- Adjust namespace
> XEP-0272: Update to adjust for current XMPP protocols

- xep-0004.xml
The pre-existing specification does not differentiate between empty or absent values. As the XEP has reached the 'final' status, such definitions can not be added to this XEP now.
This commit doesn't (intend to) add new definitions. It merely documents consequences of what is the current final spec.
The intention of this change is to make explicit that users of this XEP cannot expect this distinction to be present (unless it is explicitly defined in dependant XEPs). As a result implementations can be expected to use a variety of representations.
> XEP-0004: Empty and absent values

- xep-0264.xml
They were previously unbounded integers, aka `BigInt` in some languages. This change aligns them to what is currently allowed in XEP-0084 and XEP-0221 for instance.
> XEP-0264: Restrict 'width' and 'height' to the 0..65535 range

- xep-0313.xml
It had duplicated ids, and the JIDs of the witches weren’t consistent with their definition in XEP-0045.
These issues were found while writing #1320.
> XEP-0313: Fix MUC archive example

- inbox/pubsub-node-relationships.xml
This specification describes how to establish links between pubsub nodes, allowing for optional hierarchical organization.
> Add ProtoXEP: Pubsub Node Relationships

- inbox/pubsub-extended-subscription.xml
This specification extends the XMPP PubSub protocol by introducing mechanisms for users to subscribe to an entire node hierarchy or to receive notifications on node metadata updates.
> Add ProtoXEP: Pubsub Extended Subscriptions

- inbox/pubsub-extended-discovery.xml
This specification extends the discovery requests used with the XMPP PubSub protocol by introducing mechanisms to discover linked nodes, descendants, or metadata.
> Add ProtoXEP: Pubsub Extended Discovery

- inbox/pubsub-file-sharing.xml
This specification explains how to share files and optionally include directory structures similar to filesystems over XMPP Pubsub. It leverages XMPP Pubsub to enable notifications about file changes and manage permissions, providing users with real-time updates and control mechanisms. An optional mechanism is also specified for managing uploaded files.
> Add ProtoXEP: Pubsub File Sharing

- xep-0490.xml
These changes are purely editorial.
> XEP-0490: Add the XML Schema and fix some examples

- xep-0480.xml
The xml schema had an error (element versus attribute) and the text and example was missing base64 encoding of the salt.
> XEP-0480: Fix SCRAM upgrade description and XML schema

- xep-0500.xml
This PR includes modification I was asked for after the council meeting.
> XEP-0500: first feedbacks.

- inbox/stories.xml
This new ProtoXEP extends XEP-0472: Pubsub Social Feed by defining a new Profile called Stories.
An HTML version is available here: https://movim.eu/xeps/stories.html
> New ProtoXEP: Pubsub Stories

- xep-0501.xml
This update mention pubsub#item_expire to allow the automatic expiration of the items on the server and a fallback on the clients if not set.
> XEP-0501: Add pubsub#item_expire in the node configuration

- xep-0421.xml
- Adjust wording to use semi-anonymous or pseudonymous instead of anonymous
- Explicitly mention issues arising from occupant id matching across rooms
- Add example with server secret instead of room secret
- Add some pseudocode
Diff is here: https://larma.de/xeps/xep-0421-diff.html
Note that as part of not using the term anonymous anymore, I also adjusted the title to make it more descriptive.
> XEP-0421 v0.3.0

- inbox/gateway-relayed-encryption.xml
This specification describes a mechanism for end-to-end encryption with gateways that is compatible with third-party networks.
> Add ProtoXEP: Gateway Relayed Encryption

- inbox/gre-formatter-mime.xml
This GRE Formatter uses Multipurpose Internet Mail Extensions (MIME) to format payload.
> Add ProtoXEP: GRE Formatter: MIME

- inbox/gre-encrypter-openpgp.xml
This GRE Encrypter uses OpenPGP to encrypt payload.
> Add ProtoXEP: GRE Encrypter: OpenPGP

- xep-0424.xml
- Use a XEP-0425 /me command in the fallback body
- State that a tombstone's `<retracted>` element's 'id' attribute should match the retraction message's 'id'.
- Specify XEP-0359 as a dependency and require that the stanza 'id' be used instead of the origin-id.
- Update the "Security Considerations" to mention the risk of not being able to uniquely identify which message should be retracted when retracting messages from clients that don't support XEP-0359.
https://mail.jabber.org/hyperkitty/list/standards@xmpp.org/thread/UQWBL6O3CEARWCNMBU5N7A7ZAF6VE5WS/
> XEP-0424: Modifications in response to Last-Call feedback.

- inbox/spaces.xml
A rendered version is available at https://nicoco.fr/inbox/spaces.html
This is an attempt at a minimal "spaces XEP".
I remember reading a document a long time ago which looked impressively complete but did not turn into a XEP proposal. I suspect this is because the document attempted to cover everything, and there are very different use-cases for spaces, with different permissions models, ranging from fully public to completely private through "some rooms are public but some require being part of a subteam" etc. I tried a different approach here, attempting to lay the foundation of what is the minimum to cluster several groupchats without relying on a dedicated MUC service just for that.
The slidge-based gateways for discord, mattermost and matrix already implement listing the "servers", …
> new xep: spaces

- xep.xsl
Clarify that normative RFC 2119 language MUST be in all caps.
> Update BCP 14 language to comply with RFC 8174

- .github/workflows/xep-validation.yml
The quotation made the list of files be interpreted as one very long filename.
Split off in a environment variable to better match the examples provided by tj-actions/changed-files
> CI: improve iteration over multiple changed files

- inbox/pubsub-server-info.xml
- inbox/xep-happy-eyeballs.xml
- inbox/xep-http_online_meetings.xml
- xep-0377.xml
- xep-0483.xml
- xep-0485.xml
- xep-0495.xml
- xep.ent
Introduces an additional feature that allows end-users to opt-in to processing of submitted reports.
Changes like these were discussed on the XSF's 'standards' mailing list, as archived at https://mail.jabber.org/hyperkitty/list/standards@xmpp.org/thread/RDLWOMBMT24DCH54O2HEV2S3WW67FETE/
> XEP-0377: Add report processing opt-in

- xep-0485.xml
The original specification referenced `XEP-0XXX` as no XEP number was assigned at the time of writing. This commit updates those references to XEP-0485.
> XEP-0485: Fixed references to XEP identifier.

- xep-0167.xml
'ssrc' is no generic string, but an 32-bit unsigned integer.
The XEP text also says:
> The <description/> element MAY possess a 'ssrc' attribute that
> specifies the 32-bit synchronization source for this media stream,
> as defined in RFC 3550 [2].
so I'd argue that the XEP already required 'ssrc' to be a uint32 before.
> XEP-0167: Make ssrc attribute unsignedInt instead of generic string

- xep-0317.xml
- xep.ent
As a client developper the current Hats XEP is far from be usable and feature complete.
The goal of those changes is to:
- Allow clients to develop a nice UI to manage and assign hats, for example like Discord is doing (see https://support.discord.com/hc/en-us/articles/214836687-Discord-Roles-and-Permissions)
- Reconciliate existing implementations and their specificities, see https://docs.ejabberd.im/tutorials/muc-hats/
- Those changes were meant to be backward compatible with the current 0.2.0 version
This PR make the following changes:
- Specify a urn:xmpp:hats:commands:dcreate command to add a hat to the available list
- Specify a urn:xmpp:hats:commands:ddestroy command to destroy a hat from the list
- Clarify how the service should broadcast the hat changes when it is edited, …
> XEP-0317: Hats, Update and complete the protocol

- xep-0317.xml
All those changes are just clarifications and typos except the new section that defines a way to list assigned Hats. 
- Say "room" instead of "service" when the action deals with a specific room
- In Example 1, instead of Romeo, use the same User JID than the other examples
- In Example 1, sort attributes
- Fix capitalization of "Hat title" label
- In examples, use the defined field var "hats#uri" instead of ambiguous "hat"
- Fix duplicate "should" word
- Destroy Hat: Show example how to query form with list of hats
- Listing Hats: Move to the Protocol section
- Listing Assigned Hats: New section
Thanks a lot to @badlop for his work on those changes !
Generated HTML version available there https://movim.eu/xeps/xep-0317.html :)
> XEP-0317 Hats: Typos, examples and clarifications
